/**
 * Compendium source data. Descriptions are short summaries of the mechanics; the full
 * Open Game Content rules text is on the Spheres 5E wiki page linked from each item.
 */

export const WIKI = "https://spheres5e.wikidot.com/casting-traditions";

/**
 * key, name, weight (drawback points), repeatable (may be taken twice), automated,
 * summary (description), reminder (chat reminder when spell points are spent).
 */
export const DRAWBACKS = [
  { key: "addictive-casting", name: "Addictive Casting", weight: 2,
    summary: "After spending spell points you make a Constitution saving throw (DC 8 + your previous failures). A failure gives you Mana Addiction, a penalty to your proficiency bonus that grows with repeated failures.",
    reminder: "Make a Constitution save (DC 8 + previous failures) or suffer Mana Addiction." },
  { key: "center-of-power", name: "Center of Power",
    summary: "An obvious physical feature is the source of your magic. A critical hit against you disrupts it: you lose 1d4 spell points and cannot cast for 1 round.",
    reminder: "A critical hit costs 1d4 spell points and prevents casting for 1 round." },
  { key: "charge-magic", name: "Charge Magic", weight: 2,
    summary: "After spending spell points you cannot spend more until you succeed on a d6 recharge roll. The recharge improves at 5th, 11th and 17th level.",
    reminder: "No more spell points can be spent until a d6 recharge succeeds." },
  { key: "coy-caster", name: "Coy Caster",
    summary: "When you cast while observed you must succeed on an ability check (DC 10 + 2 x spell points spent) or the action and spell points are wasted.",
    reminder: "If observed: ability check (DC 10 + 2 x SP) or the action and spell points are wasted." },
  { key: "diagram-magic", name: "Diagram Magic", weight: 2,
    summary: "You work magic through drawn diagrams (1 action per 5-foot square). Casting without a diagram requires an ability check (DC 10 + 2 x spell points spent).",
    reminder: "Without a diagram: ability check (DC 10 + 2 x SP) to cast." },
  { key: "draining-casting", name: "Draining Casting", automated: true,
    summary: "For each spell point you spend you take 1 damage and your hit point maximum is reduced by 1 (2 each from 11th level) until you finish a long rest." },
  { key: "emotional-casting", name: "Emotional Casting",
    summary: "You cannot cast sphere effects while charmed or frightened.",
    reminder: "Cannot cast while charmed or frightened." },
  { key: "extended-casting", name: "Extended Casting", weight: 2,
    summary: "Your casting takes longer: you cannot move in a turn you cast with an action, bonus action casting becomes an action, reactions use your next bonus action, and longer casting times increase by one step.",
    reminder: "Casting time is one step longer and you cannot move in the turn you cast." },
  { key: "focus-casting", name: "Focus Casting",
    summary: "You need a focus item (wand, ring, holy symbol and so on) to cast. Without it you must succeed on an ability check (DC 10 + 2 x spell points spent).",
    reminder: "Without your focus: ability check (DC 10 + 2 x SP) to cast." },
  { key: "magical-signs", name: "Magical Signs",
    summary: "Your casting produces an obvious sign such as a glow or sound. Creatures within 30 feet know you are casting and which sphere you are using.",
    reminder: "Creatures within 30 ft know you cast and which sphere." },
  { key: "material-casting", name: "Material Casting", automated: true,
    summary: "You expend 1 gp of material components per spell point spent. Abilities that cost no spell points still require a component pouch." },
  { key: "marking-magic", name: "Marking Magic",
    summary: "Targets of your magic gain a visible mark that can be removed with an action or a solvent. Removing the mark ends the effect.",
    reminder: "Targets gain a visible mark; removing it ends the effect." },
  { key: "mental-focus", name: "Mental Focus",
    summary: "You lose your mental focus when charmed, frightened, incapacitated, stunned, critically hit or when you fail a concentration save, and must spend an action meditating to regain it before casting.",
    reminder: "Requires mental focus; regain it with a 1-action meditation." },
  { key: "nature-warden", name: "Nature Warden",
    summary: "You are bound to a location. Beyond a number of miles equal to your level you must succeed on an ability check (DC 10 + 2 x spell points spent) to cast. An 8-hour ritual binds you to a new location.",
    reminder: "Away from your bound location: ability check (DC 10 + 2 x SP) to cast." },
  { key: "painful-magic", name: "Painful Magic", automated: true,
    summary: "When you spend spell points you make a Constitution saving throw (DC 10 + 2 x spell points spent) or become poisoned for 1 round. Failing saves while poisoned this way can incapacitate you." },
  { key: "point-blank-effects", name: "Point-Blank Effects",
    summary: "Your magic only reaches touch range, and ranged spell attacks become melee spell attacks.",
    reminder: "Effects are limited to touch range." },
  { key: "prepared-caster", name: "Prepared Caster",
    summary: "After a long rest you assign your spell points to specific spheres and cannot spend more than you assigned to a sphere that day.",
    reminder: "Only spell points assigned to this sphere after the last long rest may be spent." },
  { key: "rigorous-concentration", name: "Rigorous Concentration", repeatable: true,
    summary: "Concentrating on your effects costs a bonus action each round (an action each round if taken twice).",
    reminder: "Concentration costs a bonus action every round (an action if taken twice)." },
  { key: "skilled-casting", name: "Skilled Casting",
    summary: "You must succeed on a chosen skill or tool check (DC 10 + 2 x spell points spent) to cast. On a failure your proficiency bonus is reduced by 1 for the effect (2 if you fail by 4 or more).",
    reminder: "Skill or tool check (DC 10 + 2 x SP); failure lowers proficiency for the effect." },
  { key: "somatic-casting", name: "Somatic Casting", repeatable: true,
    summary: "You need one free hand to cast. If taken twice you also cannot cast while wearing armor or holding a shield, or while grappled or restrained.",
    reminder: "Needs a free hand (twice: no armor, shield, grapple or restraint)." },
  { key: "terrain-casting", name: "Terrain Casting", weight: 2,
    summary: "When casting you must spend an extra spell point or increase the casting time by one step, or the surrounding land becomes blighted. Repeated blighting grows in area and duration.",
    reminder: "Spend +1 SP or a longer casting time, or blight the surrounding terrain." },
  { key: "verbal-casting", name: "Verbal Casting",
    summary: "You must speak loudly to cast. Casting breaks stealth and alerts creatures within 60 feet, and you cannot cast in silence or while deafened.",
    reminder: "Loud casting: breaks stealth, heard within 60 ft, impossible in silence." },
  { key: "wild-magic", name: "Wild Magic", automated: true,
    summary: "Your magic has a 10% chance of a wild magic surge. This does not stack with other sources of wild magic." },
  { key: "witch-marked", name: "Witch-Marked",
    summary: "A cosmetic feature reveals your magical nature. An Intelligence (Arcana) check (DC 20 - 2 x your proficiency bonus) identifies your tradition and spheres.",
    reminder: "Your mark can reveal your tradition to observers." }
];

export const BOONS = [
  { key: "aptitude", name: "Aptitude",
    summary: "You gain proficiency, or double proficiency if already proficient, with the skill or tool used for Skilled Casting." },
  { key: "bound-creature", name: "Bound Creature",
    summary: "You can cast find familiar as a ritual, and you ignore the Focus Casting penalty while within 300 feet of your familiar." },
  { key: "deathful-magic", name: "Deathful Magic",
    summary: "While at half your hit points or fewer, your proficiency bonus counts as 1 higher for your sphere effects." },
  { key: "easy-focus", name: "Easy Focus",
    summary: "You have advantage on saving throws to maintain concentration." },
  { key: "empowered-abilities", name: "Empowered Abilities",
    summary: "While you have 0 spell points, your proficiency bonus counts as 1 higher for your sphere effects." },
  { key: "fortified-casting", name: "Fortified Casting",
    summary: "You may use Constitution as your key ability if it is higher." },
  { key: "metasphere-specialist", name: "Metasphere Specialist",
    summary: "You gain the Metasphere package of the Universal sphere plus one additional metasphere talent." },
  { key: "overcharge", name: "Overcharge",
    summary: "You can gain a level of exhaustion to treat your proficiency bonus as 1 higher for your next sphere effect." },
  { key: "overwhelming-power", name: "Overwhelming Power",
    summary: "Creatures under one or more of your effects take a -1 penalty to saves against your magic (-2 under three or more)." },
  { key: "physical-magic", name: "Physical Magic",
    summary: "You can store sphere effects in instilled objects for others to activate until your next long rest. Requires Material Casting." },
  { key: "ritualist", name: "Ritualist",
    summary: "You gain a ritual book with two 1st-level ritual spells and can copy rituals you find (2 hours and 50 gp per spell level)." },
  { key: "spellbook", name: "Spellbook",
    summary: "You attune to a spellbook or ritual book and, a limited number of times per long rest, cast a spell from it by spending spell points equal to half its level. Requires Prepared Caster." },
  { key: "terrain-defiler", name: "Terrain Defiler",
    summary: "When you increase the severity of blighted terrain, your proficiency bonus counts as 1 higher for that effect." },
  { key: "wild-surge", name: "Wild Surge",
    summary: "You can double your wild magic chance to treat your proficiency bonus as 1 higher for your next sphere effect." }
];

/**
 * Sample casting traditions. `drawbacks` entries are keys, or [key, count] for drawbacks taken twice.
 */
export const TRADITIONS = [
  { name: "Addled", kam: ["cha"], drawbacks: ["addictive-casting", "verbal-casting", "wild-magic"], boons: ["easy-focus"],
    bonus: "Mind, Illusion", flavor: "Wanderers touched by divine madness who channel chaotic power." },
  { name: "Artificery", kam: ["int"], drawbacks: ["focus-casting", "skilled-casting"], boons: ["aptitude"],
    bonus: "Creation, Enhancement", flavor: "Crafters who infuse magic into their work through tools.", note: "Focus and skill: artisan's tools." },
  { name: "Alchemy", parent: "Artificery", kam: ["int"], drawbacks: ["focus-casting", "material-casting", "prepared-caster", "skilled-casting"],
    boons: ["aptitude", "physical-magic"], bonus: "Two of Alteration, Destruction, Enhancement, Life",
    flavor: "Alchemists who distill magic into prepared brews.", note: "Focus and skill: alchemist's supplies." },
  { name: "Bardic Magic", kam: ["cha"], drawbacks: ["skilled-casting", "somatic-casting", "verbal-casting"], boons: [],
    bonus: "Two of Dark, Divination, Enhancement, Illusion, Light, Mind", flavor: "Performers who reshape reality through music.", note: "Skill: Performance." },
  { name: "Beast Charming", parent: "Bardic Magic", kam: ["cha"], drawbacks: ["skilled-casting", "somatic-casting", "verbal-casting"], boons: [],
    bonus: "Mind and any one other", flavor: "Performers whose music bonds them with animals.", note: "Skill: Performance." },
  { name: "Song-Wielder", parent: "Bardic Magic", kam: ["cha"], drawbacks: ["skilled-casting", "verbal-casting"], boons: ["empowered-abilities"],
    bonus: "Any two", flavor: "Singers whose magic grows as they keep singing.", note: "Skill: Performance." },
  { name: "Blood Magic", kam: ["con", "int"], drawbacks: ["draining-casting", "extended-casting", ["somatic-casting", 2], "verbal-casting"],
    boons: ["deathful-magic", "fortified-casting", "overcharge"], bonus: "Any two", flavor: "Casters who pay for power with their own vitality." },
  { name: "Demonology", parent: "Blood Magic", kam: ["con", "cha"], drawbacks: ["draining-casting", "mental-focus"], boons: ["fortified-casting"],
    bonus: "Any two", flavor: "Fiend-bound casters channelling power through pacts." },
  { name: "Chaos Tapper", kam: ["cha"], drawbacks: ["addictive-casting", "magical-signs", "painful-magic", "wild-magic"], boons: ["wild-surge"],
    bonus: "Universal (Wild Magic package) and one other", flavor: "Reckless casters who tap raw chaos." },
  { name: "Contaminated", kam: ["cha"], drawbacks: ["addictive-casting", "material-casting", "wild-magic"], boons: ["overcharge"],
    bonus: "Two of Alteration, Enhancement, Destruction, Telekinesis, Time, Warp", flavor: "Users of magical essence who gain unstable power." },
  { name: "Diagram Alchemy", kam: ["int"], drawbacks: ["diagram-magic"], boons: ["easy-focus"],
    bonus: "Creation, Enhancement", flavor: "Practitioners who work transformations through inscribed diagrams." },
  { name: "Divine Petitioner", kam: ["wis"], drawbacks: ["focus-casting", "prepared-caster", "verbal-casting"], boons: [],
    bonus: "Two spheres tied to your deity", flavor: "Servants who petition a deity each day for their magic." },
  { name: "Divine Crusader", parent: "Divine Petitioner", kam: ["cha"], drawbacks: ["focus-casting", "prepared-caster", "verbal-casting"], boons: [],
    bonus: "Two of Divination, Life, Protection", flavor: "Champions of a divine cause rather than a single god." },
  { name: "Druidic", kam: ["wis"], drawbacks: ["prepared-caster", "verbal-casting"], boons: [],
    bonus: "Two of Alteration, Conjuration, Life, Mind, Nature, Weather", flavor: "Druids empowered by communion with nature." },
  { name: "Blighter", parent: "Druidic", kam: ["wis"], drawbacks: ["terrain-casting", "verbal-casting"], boons: ["terrain-defiler"],
    bonus: "Two of Death, Nature, Weather", flavor: "Corrupted druids who drain the land around them." },
  { name: "Ranger", parent: "Druidic", kam: ["wis"], drawbacks: ["skilled-casting", "verbal-casting"], boons: ["aptitude"],
    bonus: "Two of Enhancement, Life, Nature, Weather", flavor: "Wilderness experts whose magic comes from experience.", note: "Skill: Herbalism kit, Nature or Survival." },
  { name: "Fey Magic", kam: ["cha"], drawbacks: ["emotional-casting", ["somatic-casting", 2], "wild-magic"], boons: ["easy-focus", "overcharge"],
    bonus: "Two of Dark, Illusion, Mind, Nature, Weather", flavor: "Fey-touched casters driven by emotion and elaborate gesture." },
  { name: "Ley-line Tapper", parent: "Fey Magic", kam: ["wis"], drawbacks: ["extended-casting", "nature-warden"], boons: ["easy-focus"],
    bonus: "Nature and any one other", flavor: "Mystics drawing on a network of magical places." },
  { name: "Lycanthrope", kam: ["wis"], drawbacks: ["wild-magic"], boons: [],
    bonus: "Alteration and one Alteration (genotype) talent", flavor: "Shapeshifters whose magic comes from their bestial nature." },
  { name: "True Shapeshifter", parent: "Lycanthrope", kam: ["wis"], drawbacks: [], boons: [],
    bonus: "None; gains the Transformation feat instead", flavor: "Natural shapeshifters whose magic supports their transformations." },
  { name: "Kineticist", kam: ["con"], drawbacks: ["charge-magic", "draining-casting", "magical-signs"], boons: ["fortified-casting", "overcharge"],
    bonus: "Two from the Destruction sphere", flavor: "Casters who unleash elemental force from within." },
  { name: "Air-Rider", parent: "Kineticist", kam: ["con", "cha"], drawbacks: ["draining-casting", "mental-focus"], boons: ["fortified-casting"],
    bonus: "Two from Nature (air geomancy)", flavor: "Aeromancers who move wind with subtle focus." },
  { name: "Earth-Bound", parent: "Kineticist", kam: ["con", "wis"], drawbacks: ["draining-casting", "magical-signs", "somatic-casting"], boons: ["fortified-casting"],
    bonus: "Destruction, Nature (earth geomancy)", flavor: "Geomancers who visibly reshape the earth." },
  { name: "Flame-Blooded", parent: "Kineticist", kam: ["con", "int"], drawbacks: ["draining-casting", "magical-signs", ["somatic-casting", 2]],
    boons: ["fortified-casting", "overcharge"], bonus: "Destruction, Nature (fire geomancy)", flavor: "Casters with a volatile heritage of fire." },
  { name: "Water-Magi", parent: "Kineticist", kam: ["con", "wis"], drawbacks: ["draining-casting", "magical-signs", ["somatic-casting", 2]],
    boons: ["easy-focus", "fortified-casting"], bonus: "Nature (water geomancy), Telekinesis", flavor: "Disciplined water-shapers following the tides." },
  { name: "Mysticism", kam: ["wis"], drawbacks: ["magical-signs", "verbal-casting"], boons: ["empowered-abilities"],
    bonus: "Fate and any one other", flavor: "Spiritual students whose magic visibly calls on higher powers." },
  { name: "Monastic", parent: "Mysticism", kam: ["con", "wis"], drawbacks: ["draining-casting", "magical-signs", "point-blank-effects", "somatic-casting"],
    boons: ["fortified-casting", "metasphere-specialist"], bonus: "Any two", flavor: "Monks who cultivate magic through meditation and training." },
  { name: "Natural", kam: ["cha"], drawbacks: [], boons: [],
    bonus: "Any two", flavor: "Creatures with inborn magic and no formal tradition." },
  { name: "Pact Magic", kam: ["cha"], drawbacks: ["addictive-casting"], boons: ["easy-focus"],
    bonus: "Conjuration and one suited to your patron", flavor: "Casters whose patron's servants work magic on their behalf." },
  { name: "Psychic", kam: ["int"], drawbacks: ["emotional-casting", "rigorous-concentration"], boons: [],
    bonus: "Mind, Telekinesis", flavor: "Minds that turn willpower into force." },
  { name: "Runist", kam: ["int"], drawbacks: ["extended-casting", "skilled-casting", ["somatic-casting", 2]], boons: [],
    bonus: "Any two", flavor: "Scholars of a primordial language of runes.", note: "Skill: calligrapher's supplies." },
  { name: "Sorcerous Blood", kam: ["cha"], drawbacks: ["somatic-casting", "verbal-casting"], boons: [],
    bonus: "Any two suited to your heritage", flavor: "Heirs of magical bloodlines who command power by word and gesture." },
  { name: "Inherent Divinity", parent: "Sorcerous Blood", kam: ["cha"], drawbacks: ["emotional-casting", "verbal-casting"], boons: ["easy-focus"],
    bonus: "Two spheres tied to your divine ancestor", flavor: "Divine-blooded casters who reshape reality by declaration." },
  { name: "Wild-Born", parent: "Sorcerous Blood", kam: ["cha"], drawbacks: ["focus-casting", "verbal-casting"], boons: ["bound-creature"],
    bonus: "Any two", flavor: "Casters raised by magical creatures who draw on that bond." },
  { name: "Wild Magic", parent: "Sorcerous Blood", kam: ["cha"], drawbacks: ["magical-signs", "wild-magic"], boons: ["wild-surge"],
    bonus: "Universal (Wild Magic package) and one other", flavor: "Casters who embrace unpredictable surges." },
  { name: "Traditional Magic", kam: ["int"], drawbacks: ["material-casting", "prepared-caster", ["somatic-casting", 2], "verbal-casting"], boons: [],
    bonus: "Any two", flavor: "Academic casters bound by rituals and prescribed rites." },
  { name: "Magus", parent: "Traditional Magic", kam: ["int"], drawbacks: ["material-casting", "somatic-casting", "verbal-casting"], boons: ["empowered-abilities"],
    bonus: "Any two", flavor: "Martial scholars who keep their gestures even in armor." },
  { name: "Occultist", parent: "Traditional Magic", kam: ["int"], drawbacks: ["focus-casting", ["somatic-casting", 2], "verbal-casting"],
    boons: ["easy-focus", "empowered-abilities"], bonus: "Any two", flavor: "Casters who channel magic through relics and precise words." }
];
