/** Magic spheres F-W. Same format as spheres-a.mjs. */

const NO_CONC = { key: "noConc", label: "Lasts without concentration", cost: 2 };

export const SPHERES_B = [
  {
    key: "fate", name: "Fate",
    summary: "Bend luck and cosmic law with consecrations, motifs and words.",
    abilities: [
      { key: "consecration", name: "Consecration", type: "utility", activation: "action", range: "self", template: ["radius", 10],
        duration: [1, "minute", true],
        summary: "Radiate a 10 ft aura (larger at 5th, 11th and 17th level) that moves with you and applies one consecration talent.",
        groups: { consecration: "Consecration" }, augments: [NO_CONC] },
      { key: "motif", name: "Motif", type: "utility", activation: "minute", activationValue: 10, range: "touch",
        duration: [1, "hour", true],
        summary: "Grant a creature a cosmic motif.",
        groups: { motif: "Motif" },
        augments: [{ key: "action", label: "Motif as an action", cost: 1 }, NO_CONC] },
      { key: "word", name: "Word", type: "utility", activation: "action", range: 30, duration: [0, "inst", false],
        summary: "Speak a word of power at a creature or object.",
        groups: { word: "Word" },
        augments: [{ key: "bonus", label: "Speak as a bonus action", cost: 1 }] }
    ],
    talents: [
      ["Champion's Mantle", "consecration", 0, "Allies inside deal +1d4 radiant damage with weapons."],
      ["Consequences", "consecration", 0, "Creatures that attack inside take psychic damage equal to your proficiency bonus once per round."],
      ["Divine Force", "consecration", 0, "Creatures of an opposed alignment must save or suffer a random condition."],
      ["Hallow", "consecration", 0, "Supernatural creatures have disadvantage attacking your allies."],
      ["Logos", "consecration", 0, "Everyone inside understands spoken words."],
      ["Misfortune", "consecration", 0, "Hostile creatures entering must save or subtract 1d4 from attacks and saves."],
      ["Purity", "consecration", 0, "Allies have advantage on Wisdom saves and death saves."],
      ["Reveal Alignment", "consecration", 0, "Alignments inside become visible."],
      ["Serendipity", "consecration", 0, "Allies add 1d4 to an attack or save once per round."],
      ["Silence", "consecration", 0, "Creatures inside are deafened, resist thunder and cannot use verbal components."],
      ["Tug Fate", "consecration", 0, "d20 rolls of 10+ gain a bonus or penalty equal to your proficiency bonus."],
      ["Undo Harm", "consecration", 0, "The first damage each round grants 5 temporary hit points (up to 35)."],
      ["The Chariot", "motif", 0, "Advantage on saves against incapacitating conditions."],
      ["The Devil", "motif", 0, "Assess an opponent's strength each round."],
      ["The Emperor", "motif", 0, "Reduce penalties to your rolls."],
      ["The Empress", "motif", 0, "Gain a temporary inspiration."],
      ["The Fool", "motif", 0, "Disadvantage on saves but a +5 bonus."],
      ["The Hanged Man", "motif", 0, "Double proficiency on one save at the cost of others."],
      ["The Hermit", "motif", 0, "Help yourself as a bonus action when alone."],
      ["The Hierophant", "motif", 0, "Allies within 30 ft have advantage against charm."],
      ["Judgment", "motif", 0, "You cannot be surprised and invisibility gives foes no advantage."],
      ["Justice", "motif", 0, "Mark the first creature to damage you each round for +1d6 weapon damage."],
      ["The Lovers", "motif", 0, "Bonus to saves for each adjacent ally."],
      ["The Magician", "motif", 0, "Add half proficiency to checks you are not proficient in."],
      ["The Moon", "motif", 0, "Advantage against illusions."],
      ["The Star", "motif", 0, "Attacks against you during your turn have disadvantage."],
      ["Strength", "motif", 0, "Use a higher ability instead of Strength for checks."],
      ["The Sun", "motif", 0, "Advantage on saves while below half hit points."],
      ["Temperance", "motif", 0, "Reroll natural 1s."],
      ["The Tower", "motif", 0, "Unarmed and natural attacks ignore resistance."],
      ["The Wheel", "motif", 0, "Roll for a random bonus to attacks, saves or checks."],
      ["The World", "motif", 0, "Treat low d20 rolls on proficient checks as 10."],
      ["Bless", "word", 0, "The target has advantage on its next d20 roll."],
      ["Bondage", "word", 0, "Save or restrained until your next turn."],
      ["Curse", "word", 0, "The target has disadvantage on its next d20 roll."],
      ["Exorcise", "word", 0, "A new save against domination or possession."],
      ["Freedom", "word", 0, "Automatically escape and ignore restraining conditions this round."],
      ["Harm", "word", 0, "Damage to the target increases by your proficiency bonus for 1 round."],
      ["Mark", "word", 0, "Hits deal +1d6 necrotic to the target for 1 minute."],
      ["Mercy", "word", 0, "The target must knock out rather than kill for 1 hour."],
      ["Open/Close", "word", 0, "Open or close a door, container, eyes or mouth."],
      ["Soothe", "word", 0, "Healing the target receives increases by your proficiency bonus."],
      ["Subvert", "word", 0, "The target's next damage may be turned on itself."],
      ["Violence", "word", 0, "Save or attack the nearest creature next turn."],
      ["Bound Consecration", "other", 0, "Leave a consecration in place or bind it to an object."],
      ["Atonement", "word", 1, "Restore a creature to its original alignment."],
      ["Consecrated Ground", "consecration", 1, "A stationary consecration lasts 8 hours or permanently.", { cost: 2 }],
      ["Death", "motif", 1, "Linked motifs may survive dismissal."],
      ["Execration", "word", 1, "Curse words last until dispelled.", { cost: 3 }],
      ["The High Priestess", "motif", 1, "Share a motif's benefit with allies within 30 ft."]
    ]
  },
  {
    key: "illusion", name: "Illusion",
    summary: "Create figments and glamers that deceive the senses.",
    abilities: [
      { key: "figment", name: "Figment", type: "utility", activation: "action", range: 60, template: ["cube", 10],
        duration: [10, "minute", true],
        summary: "Create a silent visual illusion in a 10 ft cube (larger at 5th, 11th and 17th level). Creatures disbelieve with an Intelligence (Investigation) check against your sphere DC.",
        groups: { figment: "Figment talent" },
        augments: [{ key: "sound", label: "Add sound", cost: 1 }, { key: "size", label: "Increase size", cost: 1 }, NO_CONC] },
      { key: "glamer", name: "Glamer", type: "utility", activation: "action", range: 60, duration: [10, "minute", true],
        summary: "Place an illusion on a creature or object using a glamer talent. Glamers usually cannot be disbelieved.",
        groups: { glamer: "Glamer" }, augments: [NO_CONC] }
    ],
    talents: [
      ["Decoy", "glamer", 0, "Illusory duplicates may take hits (11+ on a d20)."],
      ["Illusionary Disguise", "glamer", 0, "Change the target's appearance within its body shape."],
      ["Obscure", "glamer", 0, "Attacks against the target have disadvantage; augments grant invisibility and more."],
      ["Greater Illusions", "sensory", 0, "Figments can include smell, taste and touch."],
      ["Veiled Illusions", "sensory", 0, "Figments can have a false aura or none."],
      ["Illusionary Obstruction", "figment", 0, "An obstruction that blocks senses and cannot be disbelieved."],
      ["Complex Illusions", "other", 0, "Split a figment into several smaller illusions."],
      ["Control Figment", "other", 0, "Take control of another caster's figment."],
      ["Illusionary Terrain", "figment", 0, "Alter the look of terrain."],
      ["Insistent Illusions", "other", 0, "A creature has disadvantage on its next disbelief check."],
      ["Potent Illusions", "figment", 0, "Figments can blind, deafen, poison, frighten, charm or deal 1d4-4d4 psychic damage (Intelligence save).", { cost: 1 }],
      ["Programmed Illusion", "figment", 0, "A figment that triggers on a condition."],
      ["Selective Illusions", "other", 0, "Chosen creatures see through or are unaffected by your figments."],
      ["Intelligent Illusions", "sensory", 1, "Figments act independently and disguises fool mind reading."],
      ["Mirage", "figment", 1, "Figments up to a 1 mile cube (11th level).", { cost: 2 }],
      ["Permanent Illusion", "other", 1, "Figments and glamers last indefinitely (11th level).", { cost: 4, applies: ["figment", "glamer"] }],
      ["Shadow Infusion", "other", 1, "Potent illusions can grapple, restrain or deal other damage (5th level)."],
      ["Illusionary Combatants", "figment", 0, "Grant allies advantage or foes disadvantage on attacks inside the figment.", { cost: 1 }],
      ["Illusionary Cover", "figment", 0, "Fog or walls that heavily obscure the area.", { cost: 1 }],
      ["Illusionary Distraction", "figment", 0, "Chosen creatures inside have disadvantage on Perception.", { cost: 1 }]
    ]
  },
  {
    key: "life", name: "Life",
    summary: "Heal wounds, grant vitality and remove afflictions.",
    abilities: [
      { key: "cure", name: "Cure", type: "heal", activation: "action", range: "touch", cost: 1, duration: [0, "inst", false],
        heal: { key: "cure", type: "healing" },
        summary: "Restore 1d8 + your key ability modifier hit points (2d8 at 5th, 3d8 at 11th, 4d8 at 17th level).",
        augments: [] },
      { key: "invigorate", name: "Invigorate", type: "heal", activation: "action", range: "touch", duration: [1, "hour", false],
        heal: { key: "invigorate", type: "temphp" },
        summary: "Grant temporary hit points equal to your proficiency bonus for 1 hour and stabilize a dying creature.",
        augments: [{ key: "extend", label: "Lasts until used up or a long rest", cost: 1 }] },
      { key: "restore", name: "Restore", type: "utility", activation: "action", range: "touch", cost: 1, duration: [0, "inst", false],
        summary: "End one disease or the blinded, deafened, paralyzed or poisoned condition.",
        augments: [] }
    ],
    talents: [
      ["Adrenaline Surge", "other", 0, "The healed creature can use its reaction to attack, move, escape or draw a weapon.", { cost: 1, applies: ["cure", "invigorate", "restore"] }],
      ["Break Enchantment", "other", 0, "Restore can end a magical effect with a check against its DC.", { cost: 1, applies: ["restore"] }],
      ["Contagion", "other", 0, "Transfer a removed condition to another creature (Constitution save).", { cost: 1, applies: ["restore"] }],
      ["Diagnose", "other", 0, "Identify the conditions affecting a creature."],
      ["Empathic Healing", "other", 0, "Take a condition onto yourself instead; costs 1 spell point less.", { cost: -1, applies: ["restore"] }],
      ["Esoteric Healing", "other", 0, "Cure can heal undead and constructs.", { cost: 0, applies: ["cure"] }],
      ["Fount of Life", "other", 0, "Store cure healing (up to 10 x your level) to use later without spell points."],
      ["Greater Healing", "other", 0, "Cure heals 5 x your level + key ability modifier instead.", { cost: 1, applies: ["cure"], healFlat: true }],
      ["Greater Invigorate", "other", 0, "Invigorate grants 5 temporary hit points (10 at 5th, 15 at 11th, 20 at 17th) that may exceed your maximum.", { cost: 1, applies: ["invigorate"], tempFlat: true }],
      ["Greater Restore", "other", 0, "Restore also reduces exhaustion or restores ability scores and maximum hit points.", { cost: 1, applies: ["restore"] }],
      ["Latent Healing", "other", 0, "Delay a cure or invigorate until the target triggers it as a reaction.", { cost: 0, applies: ["cure", "invigorate"] }],
      ["Restorative Cure", "other", 0, "Combine cure or invigorate with restore on the same target.", { cost: 1, applies: ["cure", "invigorate"] }],
      ["Restore Mind", "other", 0, "Restore can also end charmed, frightened, stunned or unconscious.", { cost: 1, applies: ["restore"] }],
      ["Restore Movement", "other", 0, "Restore can end petrified, restrained or slowing effects.", { cost: 1, applies: ["restore"] }],
      ["Resuscitate", "other", 0, "Revive a creature that died within the last round (2 spell points) or minute (3).", { cost: 2 }],
      ["Revitalize", "other", 0, "Cure instead heals 1 hit point per round (up to 4) for 1 minute.", { cost: 0, applies: ["cure"] }],
      ["Regeneration", "other", 1, "Reattach or regrow severed limbs (11th level).", { cost: 1 }],
      ["Restore Mind and Body", "other", 1, "Restore removes any number of conditions (11th level).", { cost: 2, applies: ["restore"] }],
      ["Resurrection", "other", 1, "Return a creature dead up to 10 days to life (1 hour, 11th level).", { cost: 3 }],
      ["Resurrection, Greater", "other", 1, "Return a creature dead up to 100 years (15th level).", { cost: 1 }]
    ]
  },
  {
    key: "light", name: "Light",
    summary: "Create and manipulate light to reveal, blind and burn.",
    abilities: [
      { key: "glow", name: "Glow", type: "utility", activation: "action", range: 120, duration: [10, "minute", false],
        summary: "Make a creature or object shed bright light 5 ft and dim light 15 ft, outlining it and defeating invisibility. Unwilling targets require a spell attack.",
        groups: { glow: "Glow talent", nimbus: "Nimbus" } },
      { key: "brighten", name: "Brighten", type: "utility", activation: "bonus", range: 120, save: "wis", duration: [1, "minute", true],
        summary: "Increase a glow's bright and dim light by 20 ft (more at higher levels).",
        augments: [{ key: "multi", label: "Brighten several glows", cost: 1 }] },
      { key: "lens", name: "Lens", type: "utility", activation: "action", range: 120, duration: [1, "hour", true],
        summary: "Bend light around a target using a lens talent.",
        groups: { lens: "Lens" }, augments: [NO_CONC] }
    ],
    talents: [
      ["Beacon of Hope", "glow", 0, "Advantage on saves against being frightened."],
      ["Blinding Light", "glow", 0, "Attack and Perception penalty; brightened glows can blind (Constitution save)."],
      ["Bound Light", "glow", 0, "Restrain the target and block teleportation when brightened.", { cost: 1 }],
      ["Disorienting Patterns", "glow", 0, "Bright light becomes difficult terrain; Wisdom save or fall prone."],
      ["Encompassing Light", "glow", 0, "+1d4 damage and +5 ft reach when brightened."],
      ["Flicker", "glow", 0, "Pass through transparent objects when brightened."],
      ["Guiding Light", "glow", 0, "Attacks against the glowing target have advantage.", { cost: 1 }],
      ["Hypnotic Light", "glow", 0, "Charisma save or stare, taking no actions."],
      ["Lure Light", "glow", 0, "Wisdom save or move toward the light."],
      ["Irradiance", "glow", 0, "Constitution save or 1d6 poison damage each turn.", { cost: 1 }],
      ["Repelling Light", "glow", 0, "A chosen creature type cannot approach (Constitution save).", { cost: 1 }],
      ["Revealing Light", "glow", 0, "Invisible things in bright light lose invisibility.", { cost: 1 }],
      ["Searing Light", "glow", 0, "1d4 radiant damage per round in bright light (Constitution save for half)."],
      ["Sunstroke", "glow", 0, "1d4 radiant damage each round and possible exhaustion.", { cost: 1 }],
      ["Visual Overload", "glow", 0, "Wisdom save or only an action or bonus action."],
      ["Chameleon", "lens", 0, "Advantage on Stealth."],
      ["Dim Light", "lens", 0, "Immunity to harmful light effects."],
      ["Infravision", "lens", 0, "See warm-blooded creatures through obscurement."],
      ["Obscure", "lens", 0, "As a reaction, impose disadvantage on an attack."],
      ["Periscope", "lens", 0, "See through bent lines of light."],
      ["Telescope", "lens", 0, "No long-range disadvantage and advantage on sight-based Perception."],
      ["Beam", "nimbus", 0, "Shape the glow into a 5 ft wide, 20 ft line."],
      ["Illuminate", "nimbus", 0, "Shape the glow into a 10 ft cone."],
      ["Trail", "nimbus", 0, "Leave a trail of light where the target moves."],
      ["Area Glow", "other", 0, "Glow everything in a 15 ft radius (Dexterity save).", { cost: 1, applies: ["glow"] }],
      ["Bend Radiance", "other", 0, "Exclude areas from your glow's light."],
      ["Black Light", "other", 0, "Glows shed invisible light that ignores magical darkness."],
      ["Dancing Lights", "other", 0, "Create free-floating lights that move 60 ft per round."],
      ["Dual Light", "other", 0, "Apply two glow or lens talents at once.", { cost: 1, applies: ["glow", "lens"] }],
      ["Flare", "other", 0, "Detonate a glow for 1d8 radiant damage."],
      ["Flash", "other", 0, "Trigger glow effects at any point during your turn."],
      ["Glory", "other", 0, "Brighten your own glow without concentration."],
      ["Intensity Control", "other", 0, "Change a glow's radius by 10 ft."],
      ["Light Link", "other", 0, "Always know where your glows are."],
      ["Style", "other", 0, "Colored and patterned glows."],
      ["Daylight", "glow", 1, "Bright light across 2 miles (11th level).", { cost: 2 }],
      ["Diffuse Body", "other", 1, "Split your position when moving with Flicker.", { cost: 2 }]
    ]
  },
  {
    key: "mind", name: "Mind",
    summary: "Charm, command and read the minds of others.",
    abilities: [
      { key: "charm", name: "Charm", type: "save", activation: "action", range: 30, save: "wis", duration: [1, "minute", true],
        summary: "Apply a charm talent to a creature of your type (Wisdom save negates). Lesser charms cost nothing but work once per target per rest; greater charms cost 1 spell point, powerful charms 2 (requires Powerful Charm).",
        groups: { charm: "Charm" },
        augments: [{ key: "greater", label: "Greater charm", cost: 1 },
          { key: "powerful", label: "Powerful charm (instead of greater)", cost: 2, talent: "Powerful Charm", replaces: "greater" }] }
    ],
    talents: [
      ["Amnesia", "charm", 0, "Erase memories, from 1 round (lesser) to a week (powerful)."],
      ["Calm", "charm", 0, "Suppress hostility and rage."],
      ["Candor", "charm", 0, "Compel truthful speech or answers."],
      ["Command", "charm", 0, "Control the target's actions using your own."],
      ["Confusion", "charm", 0, "The target acts randomly."],
      ["Courage", "charm", 0, "The target adds 1d4 to attacks and checks."],
      ["Disrupt Focus", "charm", 0, "Force concentration saves or block spellcasting."],
      ["Enthrall", "charm", 0, "The target regards you as a friend."],
      ["Fear", "charm", 0, "The target is frightened."],
      ["Gestures", "charm", 0, "Somatic components may fail; powerful gives near-total motor control."],
      ["Hostility", "charm", 0, "The target attacks the nearest creature or itself."],
      ["Inception", "charm", 0, "Plant false memories or rumors."],
      ["Inspiration", "charm", 0, "Add 1d4 (2d4 greater) to a roll after it is made."],
      ["Mind Shield", "charm", 0, "Proficiency on Wisdom saves; powerful grants immunity to enchantment."],
      ["Mind Spy", "charm", 0, "See and hear through the target's senses."],
      ["Paralyze", "charm", 0, "Restrain (lesser), stun (greater) or paralyze (powerful)."],
      ["Project Thoughts", "charm", 0, "Send telepathic messages."],
      ["Read Mind", "charm", 0, "Sense emotions, surface thoughts or specific information."],
      ["Sleep", "charm", 0, "Make the target lethargic, asleep or deeply asleep."],
      ["Suggestion", "charm", 0, "Plant a simple idea the target follows as its own."],
      ["Utterances", "charm", 0, "Disrupt verbal components or control the target's speech."],
      ["Expanded Charm", "other", 0, "Charm creatures of any type."],
      ["Powerful Charm", "other", 0, "Unlock powerful charms for 2 spell points."],
      ["Subtlety", "other", 0, "Targets may not notice a failed charm."],
      ["Cloud Mind", "charm", 1, "A creature becomes unaware of one target (5th level)."],
      ["Greater Communication", "other", 1, "Project thoughts across any distance, even planes (11th level)."],
      ["Insanity", "charm", 1, "Lasting madness after Confusion ends (11th level)."],
      ["Memetic Link", "other", 1, "An enthralled target can spread your mind effects (11th level)."],
      ["Mind Control", "charm", 1, "Powerful Enthrall lasts a week and lets you dominate the target (11th level)."]
    ]
  },
  {
    key: "nature", name: "Nature",
    summary: "Command earth, fire, water, air, metal and plants through geomancy and spirit.",
    abilities: [
      { key: "geomancy", name: "Geomancy", type: "utility", activation: "action", range: 30, duration: [1, "minute", true],
        summary: "Use one geomancy ability from your packages (air, earth, fire, metal, plant or water).",
        groups: { geomancy: "Geomancy talent" }, augments: [NO_CONC] },
      { key: "spirit", name: "Spirit", type: "utility", activation: "action", range: "self", duration: [10, "minute", true],
        summary: "Gain one spirit ability.",
        groups: { spirit: "Spirit" },
        augments: [{ key: "bonus", label: "Cast as a bonus action", cost: 1 }, NO_CONC] }
    ],
    talents: [
      ["Air Package", "package", 0, "Breeze, Gust of Wind and Purify Air geomancy."],
      ["Earth Package", "package", 0, "Bury, Sandblast and Tremor geomancy."],
      ["Fire Package", "package", 0, "Affect Fire, Move Fire and Quick Light geomancy."],
      ["Metal Package", "package", 0, "Magnetize, Recover Ore and Reforge geomancy."],
      ["Plant Package", "package", 0, "Entangle, Harvest and Pummel geomancy."],
      ["Water Package", "package", 0, "Fog, Freeze and Vortex geomancy."],
      ["Air Mastery", "geomancy", 0, "Gust becomes a cone; gain Absorbing Inhalation and Feather Fall."],
      ["Create Nature", "geomancy", 0, "Create elemental material in 10 to 25 ft cubes.", { cost: 1 }],
      ["Destroy Elements", "geomancy", 0, "Steal breath, shatter, extinguish, oxidize, decompose or dehydrate."],
      ["Earth Mastery", "geomancy", 0, "Granulate stone, turn earth to sandstone or pull things from the ground."],
      ["Elevated Nature", "geomancy", 0, "Geomancy reaches above and below you."],
      ["Fire Mastery", "geomancy", 0, "Alter firelight or create spreading flames (1d8 fire)."],
      ["Fog Mastery", "geomancy", 0, "Fog becomes blades, sandstorms, smoke, acid rain, spores or solid fog."],
      ["Forge Earth", "geomancy", 0, "Excavate, inscribe or reshape terrain."],
      ["Hazardous Terrain", "geomancy", 0, "Turn your geomancy into damaging terrain."],
      ["Lava Mastery", "geomancy", 0, "Work with lava: earth ovens, moving lava or melting earth."],
      ["Manipulate Nature", "geomancy", 0, "Air geysers, stone sculpting, selective flames, shelters and waves."],
      ["Metal Mastery", "geomancy", 0, "Recover metals, pin-ball attacks and fortify objects."],
      ["Plant Mastery", "geomancy", 0, "Larger entangles, healing berries and grasping vines."],
      ["Pummel Mastery", "geomancy", 0, "Stronger and ranged pummel attacks."],
      ["Reforge Mastery", "geomancy", 0, "Chill or heat metal (1d8) and alter weapon edges."],
      ["Thermoturgy", "geomancy", 0, "Ash strikes, boiling water and safe trails through fire."],
      ["Water Mastery", "geomancy", 0, "Snow, cold snaps, moving water and purification."],
      ["Beast Friend", "spirit", 0, "Befriend beasts and call one to you."],
      ["Dragonlung", "spirit", 0, "A 2d6 breath weapon (recharge 5-6)."],
      ["Meld with Nature", "spirit", 0, "Step into earth, metal, plants or water."],
      ["Nature's Carapace", "spirit", 0, "Elemental protection such as stoneskin, barkskin or a flame mantle."],
      ["Nature's Motion", "spirit", 0, "Walk on air, water or through terrain freely."],
      ["Nature's Weapon", "spirit", 0, "Elemental attacks such as stone fists or flaming weapons."],
      ["Nature Sight", "spirit", 0, "See through fog, stone, flame, metal, plants or water."],
      ["Resist Elements", "spirit", 0, "Resistance to your package's element."],
      ["Speak With Beasts", "spirit", 0, "Communicate with beasts.", { cost: 1 }],
      ["Speak With Elements", "spirit", 0, "Communicate with clouds, stone, fire, metal, plants or water.", { cost: 1 }],
      ["Expanded Geomancy", "other", 0, "Gain another Nature package. Can be taken more than once."],
      ["Master of Elements", "other", 0, "Count as having three more packages."],
      ["Earthquake", "geomancy", 1, "A 100 ft radius earthquake (15th level).", { cost: 3 }],
      ["Freezing Geyser", "geomancy", 1, "A boiling geyser (5d6 fire) that snap-freezes (15th level).", { cost: 3 }],
      ["Natural Ally", "spirit", 1, "Summon beasts, elementals, fey or plants (5th level).", { cost: 3 }],
      ["Persistent Cloud", "geomancy", 1, "Fog effects become permanent (11th level)."],
      ["Phoenix Resurgence", "spirit", 1, "Explode at 0 hit points and return next turn (5th level).", { cost: 3 }],
      ["Rapid Growth", "geomancy", 1, "Turn a mile of land into forest or boost farmland (15th level).", { cost: 3 }],
      ["Tsunami", "geomancy", 1, "A huge wave dealing 6d10 bludgeoning (15th level).", { cost: 2 }],
      ["Volcano", "geomancy", 1, "A lava spout dealing 10d6 fire (15th level).", { cost: 3 }],
      ["Whispering Wind", "spirit", 1, "Send a message over miles on the wind.", { cost: 2 }],
      ["Wildfire", "geomancy", 1, "A 1000 ft burst of 2d8 fire (5th level).", { cost: 3 }]
    ]
  },
  {
    key: "protection", name: "Protection",
    summary: "Shield allies with aegises and wards.",
    abilities: [
      { key: "aegis", name: "Aegis", type: "utility", activation: "action", range: "touch", save: "wis", duration: [1, "hour", true],
        summary: "Grant a creature a protective aegis. Armored aegis sets its AC to your sphere DC (no Dexterity).",
        groups: { aegis: "Aegis" }, augments: [NO_CONC] },
      { key: "ward", name: "Ward", type: "utility", activation: "action", range: "self", template: ["cylinder", 20],
        duration: [1, "minute", true],
        summary: "Create a 20 ft radius ward. A barrier ward blocks physical attacks and movement (AC = sphere DC, 4 + level hit points).",
        groups: { ward: "Ward" }, augments: [NO_CONC] },
      { key: "succor", name: "Succor", type: "utility", activation: "reaction", range: 300, duration: [0, "inst", false],
        summary: "Dismiss a concentration-free aegis to trigger a succor effect on its bearer.",
        groups: { succor: "Succor" } }
    ],
    talents: [
      ["Breathless", "aegis", 0, "No need to breathe; resist inhaled poisons."],
      ["Bulwark", "succor", 0, "Resistance to all damage from the triggering attack."],
      ["Clarity", "ward", 0, "Suppress illusions and concealment inside."],
      ["Community", "other", 0, "Redirect up to half the damage taken by an aegis bearer to another."],
      ["Continuous", "ward", 0, "A sealed dome or sphere barrier."],
      ["Deathless", "aegis", 0, "Resist necrotic damage and automatically stabilize."],
      ["Energy Resistance", "aegis", 0, "Resistance to one energy type (for everyone inside a ward)."],
      ["Exclusion", "ward", 0, "Chosen creatures must pass a Strength check to enter."],
      ["Friendship", "aegis", 0, "Chosen creatures exclude the bearer from their area effects."],
      ["Greater", "ward", 0, "A barrier wall up to 30 ft long."],
      ["Guardian", "aegis", 0, "Nearby foes have disadvantage attacking others."],
      ["Impartiality", "aegis", 0, "Hide alignment and creature type."],
      ["Impedance", "aegis", 0, "Creatures must pass a Wisdom save to approach."],
      ["Inner Peace", "aegis", 0, "Resist psychic damage; advantage against charm and fear."],
      ["Luck", "succor", 0, "Reroll a saving throw."],
      ["Obscurity", "aegis", 0, "Protected creatures go unnoticed."],
      ["Obstruction", "aegis", 0, "Resistance to nonmagical physical damage."],
      ["Peacebound", "aegis", 0, "Violence against the target requires a Wisdom save."],
      ["Protected Health", "aegis", 0, "Resist poison; advantage against poison and disease."],
      ["Punishment", "aegis", 0, "Attackers take 1d4 psychic damage (more at higher levels)."],
      ["Repel Alignment", "ward", 0, "Fiends, celestials, fey and undead must pass a Charisma save to cross."],
      ["Resistance", "aegis", 0, "Use a reaction for advantage on a save."],
      ["Shield", "aegis", 0, "A weightless magical shield."],
      ["Slippery", "aegis", 0, "Advantage against grapples, restraints and shoves."],
      ["Spell Ward", "aegis", 0, "Advantage on saves against magic (a ward suppresses magic).", { cost: 1 }],
      ["Status", "other", 0, "Sense the condition of your aegis bearers."],
      ["Adaptation", "aegis", 1, "Immunity to environments and resistance to all damage."],
      ["Anti-Magic Aura", "ward", 1, "Spell Ward suppresses all magic around you."],
      ["Unplottable", "aegis", 1, "The target cannot be found by divination.", { cost: 3 }]
    ]
  },
  {
    key: "telekinesis", name: "Telekinesis",
    summary: "Move objects and creatures with the mind. Size limits grow as you level.",
    abilities: [
      { key: "levitate", name: "Levitate", type: "save", activation: "action", range: 30, save: "str", duration: [10, "minute", true],
        summary: "Move a target up to 20 ft each round. Unwilling creatures make a Strength save.",
        groups: { levitate: "Levitate talent" },
        augments: [{ key: "unwilling", label: "Target an unwilling creature", cost: 1 }, NO_CONC] },
      { key: "projectile", name: "Projectile", type: "attack", activation: "action", range: 30, duration: [0, "inst", false],
        damage: { key: "projectile", types: ["bludgeoning", "force"] },
        summary: "Hurl an object with a ranged spell attack. Damage depends on its size (1d4 for Tiny, up to 2d8 for Large).",
        groups: { projectile: "Projectile talent" } },
      { key: "catch", name: "Catch", type: "utility", activation: "action", range: 30, duration: [0, "inst", false],
        summary: "Stop an incoming projectile with a spell attack against its attack roll.",
        groups: { catch: "Catch talent" },
        augments: [{ key: "reaction", label: "Catch as a reaction", cost: 1 }] }
    ],
    talents: [
      ["Greater Catch", "catch", 0, "Catch several projectiles per round or create kinetic fields."],
      ["Parry", "catch", 0, "Block melee weapons."],
      ["Return", "catch", 0, "Fling caught projectiles back."],
      ["Telekinetic Maneuver", "catch", 0, "Knock moving creatures prone or grapple them."],
      ["Gravity Shift", "gravity", 0, "A 5 to 30 ft area of heavy or light gravity."],
      ["Gravity Well", "gravity", 0, "Pull creatures to a central point and grapple them."],
      ["Friction Field", "gravity", 0, "Difficult terrain that deals damage equal to your level each round."],
      ["Momentum Line", "gravity", 0, "A line that doubles movement along it."],
      ["Tether", "gravity", 0, "Keep two creatures within 30 ft of each other."],
      ["Dancing Weapon", "levitate", 0, "A levitated weapon grants +1 AC and attacks for you."],
      ["Finesse", "levitate", 0, "Perform delicate tasks remotely."],
      ["Orbit", "levitate", 0, "Objects orbit you and grant cover."],
      ["Quick Motion", "levitate", 0, "Move levitated targets without a bonus action."],
      ["Steal", "levitate", 0, "Pull objects from creatures."],
      ["Crater", "projectile", 0, "Target an area; Dexterity save for half."],
      ["Homing", "projectile", 0, "Missed projectiles keep pursuing for 1 minute.", { cost: 1 }],
      ["Kinetic Weapon", "projectile", 0, "Add your key ability modifier to projectile damage.", { bonus: "@spheres.kam" }],
      ["Manifest Force", "projectile", 0, "Hurl pure force, dealing force damage as a maximum size object.", { dt: "force" }],
      ["Mobile Projectile", "projectile", 0, "Make two attack rolls with one projectile."],
      ["Dampening Field", "other", 0, "Wrap targets in force to resist damage and falls."],
      ["Kinetic Sense", "other", 0, "Target squares you cannot see and gain blindsense."],
      ["Fly", "other", 0, "Grant a 20 to 80 ft fly speed.", { cost: 1 }],
      ["Help/Hinder", "other", 0, "Change a creature's speed and falling damage."],
      ["Telekinetic Crush", "other", 0, "Crush levitated targets for 1d6 to 4d6 force damage per round."],
      ["Call to Hand", "other", 0, "Pull an unattended object to your hand as a bonus action."],
      ["Telekinetic Swap", "other", 0, "Swap carried items or don armor instantly."],
      ["Affix", "levitate", 1, "Fix a target permanently in place (11th level).", { cost: 3 }],
      ["Effortless Telekinesis", "other", 1, "Telekinesis lasts 8 hours (11th level).", { cost: 1, applies: ["levitate"] }],
      ["Gravity Manipulation", "gravity", 1, "Remove or redirect gravity (15th level).", { cost: 2 }],
      ["Linear Acceleration", "projectile", 1, "Fire a projectile a mile for double damage (11th level).", { cost: 3 }],
      ["Puppet", "levitate", 1, "Control an unwilling creature's body (11th level).", { cost: 2 }]
    ]
  },
  {
    key: "time", name: "Time",
    summary: "Speed, slow and freeze the flow of time.",
    abilities: [
      { key: "alterTime", name: "Alter Time", type: "utility", activation: "action", range: 30, duration: [1, "minute", true],
        summary: "Apply one alter time talent to a creature.",
        groups: { alterTime: "Alter time" }, augments: [NO_CONC] }
    ],
    talents: [
      ["Adjusted Frequency", "alterTime", 0, "Haste (+2 AC, double speed) or slow (half speed, -2 AC, no reactions)."],
      ["Age", "alterTime", 0, "Age or rejuvenate a creature or object.", { cost: 1 }],
      ["Broken Time", "alterTime", 0, "Disadvantage on checks and a save to cast.", { cost: 1 }],
      ["Causality", "alterTime", 0, "Cause a random accident."],
      ["Delay Pain", "alterTime", 0, "Delay damage and effects until the target's next turn.", { cost: 1 }],
      ["Eject", "alterTime", 0, "Remove the target from time for 1 round.", { cost: 1 }],
      ["Fractured Image", "alterTime", 0, "Attacks against the target have disadvantage.", { cost: 2 }],
      ["Lethargy", "alterTime", 0, "Constitution save or gain a level of exhaustion.", { cost: 1 }],
      ["Rapid Response", "alterTime", 0, "Advantage on initiative and act while surprised."],
      ["Repetition", "alterTime", 0, "Treat a repeated check as a roll of 20."],
      ["Retroactive Preparation", "alterTime", 0, "Retroactively prepare an item, attitude or research.", { cost: 1 }],
      ["Retry", "alterTime", 0, "Make a creature redo its turn.", { cost: 2 }],
      ["Rewind Mana", "alterTime", 0, "Restore spell points to another creature."],
      ["Shift Time", "alterTime", 0, "Take an action now and lose it next turn."],
      ["Steal Time", "alterTime", 0, "Incapacitate the target for 1 round.", { cost: 1 }],
      ["Time Freeze", "alterTime", 0, "Freeze a 10 ft cube in time.", { cost: 1 }],
      ["Throttle Duration", "alterTime", 0, "Speed up or extend durations.", { cost: 1 }],
      ["Timeline Bridge", "alterTime", 0, "Advantage on Intelligence checks to recall lore."],
      ["Manipulate Healing", "other", 0, "Hasted targets spend Hit Dice as a bonus action; slowed targets stop regenerating."],
      ["Second Chance", "other", 0, "Force a reroll of a failed save.", { cost: 1 }],
      ["Time Zone", "other", 0, "Shape alter time into an area or wall."],
      ["Hasten Rest", "other", 1, "An unconscious creature gains a short rest in 10 minutes.", { cost: 2 }],
      ["Improved Fractured Image", "other", 1, "Fractured Image grants an extra bonus action (9th level).", { cost: 2 }],
      ["Past Sight", "other", 1, "View the past hour of a location.", { cost: 1 }],
      ["Query Self", "other", 1, "Ask questions of your future self.", { cost: 2 }],
      ["Reversion", "other", 1, "Let a creature retrain its last class level.", { cost: 6 }],
      ["Temporal Jailor", "other", 1, "Suspend ejected creatures indefinitely.", { cost: 4 }],
      ["Temporal Stasis", "other", 1, "Place a creature in stasis.", { cost: 3 }],
      ["Time Clone", "other", 1, "Create a clone the target controls.", { cost: 1 }],
      ["Time Stop", "other", 1, "Take 1d4 + 1 extra turns.", { cost: 4 }]
    ]
  },
  {
    key: "universal", name: "Universal",
    summary: "Magic that works across spheres: dispelling, mana, metamagic, spellcrafting and wild magic. Choose a package when you gain it.",
    abilities: [
      { key: "dispel", name: "Dispel", type: "utility", activation: "minute", activationValue: 10, range: 30, duration: [0, "inst", false],
        summary: "Dispel package: end magical effects with a check based on your proficiency bonus or spellcasting." },
      { key: "manabond", name: "Manabond", type: "attack", activation: "bonus", range: 30, duration: [10, "minute", true],
        summary: "Mana package: a ranged spell attack forms a magical link with a creature, letting you apply manabond talents each turn.",
        groups: { manabond: "Manabond" } },
      { key: "chaosAura", name: "Chaos Aura", type: "utility", activation: "action", range: "self", template: ["radius", 5],
        duration: [1, "minute", true],
        summary: "Wild magic package: creatures within 5 ft have +50% chance of wild magic." }
    ],
    talents: [
      ["Dispel Package", "package", 0, "Gain the Dispel ability."],
      ["Mana Package", "package", 0, "Gain the Manabond ability."],
      ["Metasphere Package", "package", 0, "Gain druidcraft, prestidigitation and thaumaturgy plus one metasphere talent."],
      ["Spellcrafting Package", "package", 0, "Gain a dual sphere talent (requires two magic spheres)."],
      ["Wild Magic Package", "package", 0, "Gain the Chaos Aura ability."],
      ["Disorient", "dispel", 0, "A failed counter leaves the caster disoriented."],
      ["Fool's Counterspell", "dispel", 0, "A countered caster thinks the spell worked."],
      ["Greater Dispel", "dispel", 0, "Dispel any number of effects."],
      ["Shaped Dispel", "dispel", 0, "Dispel can be shaped like a destructive blast."],
      ["Spellthief", "dispel", 0, "Take control of an effect you counter.", { cost: 1 }],
      ["Vicious Dispel", "dispel", 0, "Successful dispels deal 1d10 force damage (up to 4d10)."],
      ["Control Resistance", "manabond", 0, "Grant or remove a damage resistance."],
      ["Expunge", "manabond", 0, "Drain spell points or slots."],
      ["Flow", "manabond", 0, "Transfer spell points between you and the target."],
      ["Incompetence", "manabond", 0, "Give the target a drawback for 1 round."],
      ["Knowledge", "manabond", 0, "Lend the target a talent for 1 round."],
      ["Lifeburn", "manabond", 0, "The target takes 1d10 force damage when it casts."],
      ["Misdirection", "manabond", 0, "Redirect hostile spells between you and the target."],
      ["Presence", "manabond", 0, "Reveal the target's location."],
      ["Soulmate", "manabond", 0, "Copy harmless spells between you and the target."],
      ["Tethered", "manabond", 0, "Chain the target within manabond range."],
      ["Extended", "metasphere", 0, "Increase an effect's duration by 1 to 4 steps.", { cost: 1, appliesAll: true }],
      ["Glyph", "metasphere", 0, "Bind an effect into a glyph that triggers when entered.", { cost: 1, appliesAll: true }],
      ["Heightened", "metasphere", 0, "Effects are harder to dispel."],
      ["Lingering", "metasphere", 0, "An effect lingers briefly after concentration ends."],
      ["Mass", "metasphere", 0, "Single-target effects affect more targets.", { cost: 1, appliesAll: true }],
      ["Opportunistic", "metasphere", 0, "Cast as a reaction when an enemy provokes.", { cost: 1, appliesAll: true }],
      ["Quicken", "metasphere", 0, "Cast an action effect as a bonus action (1 on yourself, 2 on others).", { cost: 1, appliesAll: true }],
      ["Reaching", "metasphere", 0, "Increase an effect's range by one step."],
      ["Striking", "metasphere", 0, "Deliver an effect through a weapon attack.", { cost: 1, appliesAll: true }],
      ["Widen", "metasphere", 0, "Double an effect's area.", { cost: 1, appliesAll: true }],
      ["Blood Dampening", "wildMagic", 0, "Reduce your maximum hit points to prevent a wild magic event."],
      ["Careful Caster", "wildMagic", 0, "Reduce the wild magic chance of your next effect by 25%."],
      ["Chaotic Counter", "wildMagic", 0, "Countered casters risk wild magic."],
      ["Curse of Chaos", "wildMagic", 0, "A charged attack gives the target a 100% wild magic chance.", { cost: 1 }],
      ["Energy Shift", "wildMagic", 0, "Change a blast's damage type at a wild magic risk."],
      ["Greater Chaos Aura", "wildMagic", 0, "Chaos Aura gains augments."],
      ["Inspired Surge", "wildMagic", 0, "Gain a talent for 1 minute at a wild magic risk."],
      ["Manipulate Result", "wildMagic", 0, "Roll twice on a wild magic event and choose."],
      ["Overpower Resistance", "wildMagic", 0, "Impose disadvantage on saves at a wild magic risk.", { cost: 1 }],
      ["Shift Cost", "wildMagic", 0, "Reduce an effect's cost by 1 at a wild magic risk.", { cost: -1, appliesAll: true }],
      ["Shift Effect", "wildMagic", 0, "Spend spell points to adjust a wild magic roll."],
      ["Counterspell", "other", 0, "As a reaction, dispel or manabond a caster.", { cost: 2 }],
      ["Mystic Focus", "other", 0, "Spend 1 spell point to regain martial focus."],
      ["Universal Package", "other", 0, "Gain another Universal package."],
      ["Contingency", "metasphere", 1, "Set an effect to trigger on a condition within a week."],
      ["Extreme Duration", "metasphere", 1, "Extended costs 1 spell point less."],
      ["Extreme Opportunistic", "metasphere", 1, "Opportunistic costs 1 spell point less."],
      ["Extreme Reach", "metasphere", 1, "Increase range further than Reaching."],
      ["Extreme Striking", "metasphere", 1, "Striking costs 1 spell point less."]
    ]
  },
  {
    key: "warp", name: "Warp",
    summary: "Teleport and bend space.",
    abilities: [
      { key: "teleport", name: "Teleport", type: "utility", activation: "action", range: "touch", duration: [0, "inst", false],
        summary: "Teleport a willing creature 10 ft (20 ft at 5th, 30 ft at 11th, 40 ft at 17th level).",
        groups: { teleport: "Teleport talents" }, multi: ["teleport"],
        augments: [{ key: "distance", label: "Distance 30/60/90/120 ft", cost: 1 }] },
      { key: "bendSpace", name: "Bend Space", type: "utility", activation: "action", range: "touch", duration: [1, "minute", true],
        summary: "Apply a space talent to a target or location you touch.",
        groups: { space: "Space talent" } }
    ],
    talents: [
      ["Blink", "space", 0, "Attacks against or by the target may be at disadvantage for 1 minute."],
      ["Create Gap", "space", 0, "Bend space within an object to make gaps."],
      ["Distort Size", "space", 0, "The target occupies one size larger or smaller."],
      ["Extradimensional Room", "space", 0, "Create a pocket dimension of 10 ft cubes."],
      ["Extradimensional Storage", "space", 0, "A permanent extradimensional container."],
      ["Flex Space", "space", 0, "Contract or expand space."],
      ["Looped Space", "space", 0, "Trap creatures in a looping area."],
      ["Plane Manipulator", "space", 0, "Gain an anchoring aura and a banishing touch."],
      ["Spatial Reach", "space", 0, "+10 ft movement and reach."],
      ["Warp Link", "space", 0, "Always know the direction to a linked target."],
      ["Wormhole", "space", 0, "Link two areas so moving between them costs 5 ft."],
      ["Attack Portal", "teleport", 0, "Redirect an attack through a teleport."],
      ["Distant Teleport", "teleport", 0, "Augmented teleports reach 60 to 600 ft."],
      ["Emergency Teleport", "teleport", 0, "Teleport 5 ft as a reaction, gaining advantage on the save.", { cost: 1 }],
      ["Imbue Teleport", "teleport", 0, "Give a creature a teleport to use later."],
      ["Isoport", "teleport", 0, "Change orientation and remove prone."],
      ["Quick Teleport", "teleport", 0, "Teleport as a bonus action.", { cost: 1 }],
      ["Recall", "teleport", 0, "The target can return to a marked square."],
      ["Segmented Warp", "teleport", 0, "Split a teleport into two.", { cost: 1 }],
      ["Splinter", "teleport", 0, "Teleporting deals 1d8 slashing damage (more with an augment)."],
      ["Swap Placement", "teleport", 0, "Swap places with a creature at the destination."],
      ["Teleport Beacon", "teleport", 0, "Teleport to a beacon at any distance.", { cost: 1 }],
      ["Teleport Object", "teleport", 0, "Teleport objects.", { cost: 1 }],
      ["Unseeing Teleport", "teleport", 0, "Teleport without line of sight.", { cost: 1 }],
      ["Unwilling Teleport", "teleport", 0, "Teleport unwilling creatures (Wisdom save).", { cost: 1 }],
      ["Create Demiplane", "other", 1, "Create a permanent demiplane (15th level).", { cost: 3 }],
      ["Dimensional Lock", "space", 1, "Block extradimensional travel in a 40 ft cube for a week (15th level).", { cost: 2 }],
      ["Flawless Teleport", "teleport", 1, "True teleportation without error (15th level)."],
      ["Planeshift", "teleport", 1, "Teleport to other planes (11th level).", { cost: 2 }],
      ["Portal", "teleport", 1, "Create a portal between locations (5th level).", { cost: 1 }],
      ["Store Structure", "space", 1, "Store large objects in extradimensional storage (5th level).", { cost: 1 }],
      ["Teleport Army", "teleport", 1, "Teleport many targets (11th level).", { cost: 2 }],
      ["Teleport Structure", "teleport", 1, "Teleport very large objects (5th level)."],
      ["True Teleport", "teleport", 1, "Teleport up to 1000 miles (11th level).", { cost: 2 }]
    ]
  },
  {
    key: "weather", name: "Weather",
    summary: "Draw power from the weather with mantles and shrouds.",
    abilities: [
      { key: "mantle", name: "Mantle", type: "utility", activation: "minute", activationValue: 10, range: "touch",
        duration: [1, "hour", true],
        summary: "Grant a creature benefits based on the current weather severity.",
        groups: { mantle: "Mantle" },
        augments: [{ key: "action", label: "Mantle as an action", cost: 1 }, { key: "force", label: "Ignore the current weather", cost: 1 }, NO_CONC] },
      { key: "shroud", name: "Shroud", type: "save", activation: "action", range: 30, save: "con", duration: [1, "minute", true],
        summary: "Surround a creature with a weather shroud using a shroud talent.",
        groups: { shroud: "Shroud" }, augments: [NO_CONC] }
    ],
    talents: [
      ["Backlash", "mantle", 0, "Melee attackers take 1d4 weather damage (more at higher levels)."],
      ["Borne Aloft", "mantle", 0, "Levitate 10 ft in windy weather."],
      ["Flash Step", "mantle", 0, "Teleport 5 ft as a bonus action in stormy weather."],
      ["Flame Zephyr", "mantle", 0, "+5 ft speed in hot weather (more at higher levels)."],
      ["Fluidity", "mantle", 0, "Advantage on grapple checks in wet weather."],
      ["Ice Skates", "mantle", 0, "Ignore ice, mud, sand, snow and water terrain."],
      ["Sand Swimmer", "mantle", 0, "Swim through sand and gain tremorsense."],
      ["Boreal Glare", "mantle", 0, "A 1d6 cold ranged spell attack within 30 ft."],
      ["Desiccant", "mantle", 0, "+1d4 necrotic on melee hits in dry weather."],
      ["Fever", "mantle", 0, "+1d4 fire on natural weapon hits in hot weather."],
      ["Hyponatremia", "mantle", 0, "+1d4 poison on ranged hits in wet weather."],
      ["Razor Wind", "mantle", 0, "+1d4 slashing on unarmed strikes in windy weather."],
      ["Shock", "mantle", 0, "+1d4 lightning on metal weapon hits in stormy weather."],
      ["Breezespeech", "mantle", 0, "Speak with other breezespeakers at any distance."],
      ["Defibulation", "mantle", 0, "Advantage on death saves in stormy weather."],
      ["High Energy", "mantle", 0, "Temporary hit points each round in hot weather."],
      ["Ice Box", "mantle", 0, "Protection from decay and undeath in cold weather."],
      ["Light Load", "mantle", 0, "Greater carrying capacity in dry weather."],
      ["Mist Form", "mantle", 0, "Immune to opportunity attacks in wet weather."],
      ["Barometric Mantle", "mantle", 0, "Predict the weather and sense weather magic."],
      ["Clear Skies", "mantle", 0, "Treat the weather as less severe."],
      ["Gelid Body", "mantle", 0, "Resist cold and slashing damage in cold weather."],
      ["Mirage Sheen", "mantle", 0, "Resist piercing damage in hot weather."],
      ["Mummified Flesh", "mantle", 0, "Resist necrotic and bludgeoning damage in dry weather."],
      ["Nonconductive", "mantle", 0, "Resist lightning in stormy weather."],
      ["Sodden", "mantle", 0, "Resist fire and poison in wet weather."],
      ["Wind Tunnel", "mantle", 0, "Ranged attacks against you have disadvantage in windy weather."],
      ["Black Ice", "shroud", 0, "Halve the target's speed."],
      ["Diamond Dust", "shroud", 0, "1d6 cold damage at the end of each turn."],
      ["Karakaze", "shroud", 0, "-2 to AC and Dexterity saves."],
      ["Drench", "shroud", 0, "The target is soaked and slowed unless it dries off."],
      ["Drown", "shroud", 0, "1d8 bludgeoning damage at the end of each turn."],
      ["Rip Current", "shroud", 0, "Save or be grappled."],
      ["Dust Cloud", "shroud", 0, "Save each turn or be poisoned."],
      ["Illuminating Shaft", "shroud", 0, "Disadvantage on Stealth."],
      ["Sirocco", "shroud", 0, "Save or gain exhaustion."],
      ["Crackling Arc", "shroud", 0, "1d6 lightning damage to a nearby creature."],
      ["Personal Thunderhead", "shroud", 0, "1d6 thunder damage at the end of each turn."],
      ["Intensified Weather", "shroud", 0, "Apply severe weather to the target."],
      ["Battering Winds", "shroud", 0, "Disadvantage on ranged attacks and Dexterity saves."],
      ["Biting Wind", "shroud", 0, "Disadvantage on sight-based Perception."],
      ["Squamish", "shroud", 0, "Push the target 5 ft each turn."],
      ["Fata Morgana", "shroud", 0, "Disadvantage against illusions."],
      ["Glare", "shroud", 0, "Save each turn or be blinded."],
      ["Heat Stroke", "shroud", 0, "1d6 fire damage at the end of each turn."],
      ["Control Weather", "other", 1, "Change the weather severity over time."],
      ["Climate", "other", 1, "Control Weather lasts 8 hours over miles."],
      ["Stormlord", "other", 1, "Choose where lightning strikes."],
      ["Sudden Storm", "other", 1, "Change the weather every minute."]
    ]
  }
];
