/**
 * Magic spheres A-E. Each ability becomes a dnd5e activity on the sphere item.
 * Talent tuples: [name, category, advanced, summary, extra]. `extra.cost` is an augment cost in spell points,
 * `extra.dt` a damage type for blast types, `extra.bonus` a flat damage bonus formula.
 */

const NO_CONC = { key: "noConc", label: "Lasts without concentration", cost: 2 };

/** Every damage type a blast type can deal; the cast dialog picks the one that applies. */
const BLAST_TYPES = ["force", "acid", "bludgeoning", "cold", "fire", "lightning", "necrotic", "piercing", "poison",
  "psychic", "radiant", "slashing", "thunder"];

export const SPHERES_A = [
  {
    key: "alteration", name: "Alteration",
    summary: "Change the shape and traits of creatures. Shapeshift grants one trait (more at 5th, 11th and 17th level).",
    abilities: [
      { key: "shapeshift", name: "Shapeshift", type: "utility", activation: "action", range: "touch",
        duration: [10, "minute", true], save: "con",
        summary: "Transform a willing creature, applying a genotype and traits. An unwilling target makes a Constitution save.",
        groups: { genotype: "Genotype", trait: "Traits" }, multi: ["trait"],
        augments: [{ key: "unwilling", label: "Target an unwilling creature", cost: 1 }, NO_CONC] }
    ],
    talents: [
      ["Animalistic", "genotype", 0, "Four-legged beast form: 40 ft speed, 1d6 bite, AC 13 + Dex, keen scent."],
      ["Anthropomorphic", "genotype", 0, "Humanoid form with two arms and legs, 30 ft speed and speech, but no natural weapons."],
      ["Aquan", "genotype", 0, "Aquatic form: 20 ft swim speed, 1d6 bite, amphibious, AC 13 + Dex."],
      ["Avian", "genotype", 0, "Winged form: 30 ft glide, 1d4 talons, AC 12 + Dex."],
      ["Blank Form", "genotype", 0, "Keep your shape and appearance while still gaining traits."],
      ["Dragon", "genotype", 0, "Draconic form: 30 ft speed, 1d6 bite, 2d6 breath weapon, darkvision 60 ft."],
      ["Elemental", "genotype", 0, "Elemental form: 1d6 slam, AC 13 + Dex, darkvision 60 ft, cannot be knocked prone."],
      ["Object", "genotype", 0, "Animated object form with resistance to poison and psychic damage."],
      ["Ooze", "genotype", 0, "Ooze form: slam dealing extra acid, AC 16, blindsight 60 ft, cannot be knocked prone."],
      ["Orb", "genotype", 0, "Floating orb with a 30 ft hover speed and 1d4 slam."],
      ["Plant", "genotype", 0, "Plant form with blindsight 30 ft, sturdy bark and advantage on Stealth in foliage."],
      ["Serpentine", "genotype", 0, "Serpent form: 40 ft speed, climb, 1d6 bite and constrictor or venom options."],
      ["Subterranean", "genotype", 0, "Burrowing form: 15 ft burrow speed, darkvision and tremorsense."],
      ["Vermin", "genotype", 0, "Insect or spider form with climb speed, 1d6 bite and darkvision."],
      ["Aberrant Body", "trait", 0, "Traits such as acid spit, gibbering, many eyes, a mucus cloud or grappling tendrils."],
      ["Additional Limbs", "trait", 0, "Extra arms, heads, legs (+20 ft speed per pair) or tails."],
      ["Agile Body", "trait", 0, "Evasion, immunity to flanking or advantage on initiative."],
      ["Bestial Mind", "trait", 0, "Reduce the target's mind to that of a beast (Intelligence 2)."],
      ["Bestial Reflexes", "trait", 0, "Lunge, multiattack with natural weapons, pounce or trample."],
      ["Bestial Spirit", "trait", 0, "Speak with beasts, pack tactics, relentless endurance or shove as a bonus action."],
      ["Construct Traits", "trait", 0, "Metal plating, natural armor (AC 16) or resistance to spells."],
      ["Extreme Adaptation", "trait", 0, "Adapt to altitude, pressure, harsh weather or the need to breathe."],
      ["Fey Traits", "trait", 0, "Fey resilience, wild empathy with beasts or woodland stride."],
      ["Giant Traits", "trait", 0, "Catch and throw rocks (2d6 bludgeoning, 30/90 ft)."],
      ["Morphic Weapon", "trait", 0, "Fuse a held weapon into your arm so it counts as a natural weapon."],
      ["Odiferous", "trait", 0, "A nauseating spray (15 ft cone, 1d8 poison) or stench."],
      ["Outsider Traits", "trait", 0, "Celestial, demonic or devilish resistances and type."],
      ["Protean Mastery", "trait", 0, "Swap traits as a bonus action, camouflage or resistant hide."],
      ["Prickly", "trait", 0, "Spikes that damage grapplers and can be launched (1d6, 20/60 ft)."],
      ["Size Change", "trait", 0, "Grow one size category larger (more at higher levels) with bigger natural weapons and reach."],
      ["Swarm Body", "trait", 0, "Split into a swarm of Tiny creatures that resists weapon damage."],
      ["Twisted Body", "trait", 0, "Harmful twists for unwilling targets: blinding, slowing, silencing or weakening them."],
      ["Undead Traits", "trait", 0, "Blood drinking, incorporeal form or undead resistances."],
      ["Vitality", "trait", 0, "Advantage on death saves, immunity to magical sleep or healing with Hit Dice."],
      ["Enhanced Attacks", "other", 0, "Natural weapons count as magical."],
      ["Freeform Traits", "other", 0, "Use traits from two genotypes you do not have. Can be taken more than once."],
      ["Greater Transformation", "other", 0, "Grant one extra trait.", { cost: 0, applies: ["shapeshift"] }],
      ["Mimicry", "other", 0, "Study a creature for an hour to temporarily gain a matching Alteration talent."],
      ["Energy Manipulation", "trait", 1, "Grant energy immunity or impose vulnerability (11th level).", { cost: 1 }],
      ["Extreme Transformation", "other", 1, "Grants further extra traits (5th level, requires Greater Transformation)."],
      ["Fusion", "other", 1, "Merge two adjacent creatures into one body (5th level).", { cost: 2 }],
      ["Homogenize", "other", 1, "Twisted body victims below 100 hit points can be slain on a failed Constitution save (15th level).", { cost: 5 }],
      ["Permanent Transformation", "other", 1, "Make a shapeshift an instantaneous, permanent curse (17th level).", { cost: 4 }]
    ]
  },
  {
    key: "conjuration", name: "Conjuration",
    summary: "Summon a companion creature that fights and works for you.",
    abilities: [
      { key: "summon", name: "Summon", type: "utility", activation: "minute", activationValue: 10, range: "touch",
        duration: [1, "hour", true],
        summary: "Summon your companion into an empty space. It shares your initiative and takes the Dodge action unless you command it with a bonus action.",
        groups: { base: "Companion", form: "Forms" }, multi: ["form"],
        augments: [{ key: "action", label: "Summon as an action", cost: 1 }, NO_CONC] }
    ],
    talents: [
      ["Aberration", "base", 0, "A Medium aberration with a psychic aura and psionic assault."],
      ["Beast", "base", 0, "A Small beast with a bonus land, aerial, earth, resilient, vermin or water form."],
      ["Celestial", "base", 0, "A Medium celestial with a radiant smite and a healing touch."],
      ["Construct", "base", 0, "A Medium construct immune to poison that can deflect attacks."],
      ["Dragon", "base", 0, "A Small dragon with a bite and a bonus aerial or draconic form."],
      ["Elemental", "base", 0, "An air, earth, fire or water elemental with matching abilities."],
      ["Fey", "base", 0, "A Tiny fey with a mocking attack and a bonus magical or spell-warded form."],
      ["Fiend", "base", 0, "A Tiny shapechanging fiend with a bonus spell-warded form."],
      ["Giant", "base", 0, "A Medium giant that grows with your level and throws rocks."],
      ["Humanoid", "base", 0, "A Medium humanoid with the Battle form and one other form."],
      ["Monstrosity", "base", 0, "A Medium monstrosity whose forms can be swapped.", { cost: 1 }],
      ["Ooze", "base", 0, "A Medium acidic ooze with a bonus ravenous or resilient form."],
      ["Plant", "base", 0, "A Small plant that constricts and grapples but is vulnerable to fire."],
      ["Swarm", "base", 0, "A Medium swarm that resists weapon damage."],
      ["Undead", "base", 0, "A Medium undead with a draining grapple and undead fortitude."],
      ["Altered Size", "form", 0, "Change the companion's size, adjusting Strength and Dexterity by 2 per step."],
      ["Aerial Creature", "form", 0, "A fly speed of 20 ft, rising to 50 ft at 17th level."],
      ["Battle Creature", "form", 0, "Proficiency with shields and simple weapons (martial if taken twice)."],
      ["Draconic Creature", "form", 0, "A breath weapon (30 ft cone or 60 ft line) dealing 2d6, up to 5d6."],
      ["Earth Creature", "form", 0, "Burrow speed and tremorsense."],
      ["Elemental Creature", "form", 0, "Resistance and 1d4 bonus damage of one type, growing to 1d10."],
      ["Exemplary Companion", "form", 0, "+2 to one ability score, up to +8 at 17th level."],
      ["Explosive Companion", "form", 0, "Explodes on death for 2d6 (up to 8d6) in a 5 to 20 ft radius."],
      ["Evolved Companion", "form", 0, "Gain an Alteration trait without paying its augment."],
      ["Fortified Companion", "form", 0, "Proficiency in one saving throw."],
      ["Frightful Presence", "form", 0, "An action that frightens creatures nearby (Wisdom save)."],
      ["Land Creature", "form", 0, "+20 ft land speed and advantage on smell-based Perception."],
      ["Magical Companion", "form", 0, "The companion gains magical training of its own."],
      ["Mystical Companion", "form", 0, "Ki points for Flurry of Blows, Patient Defense and Step of the Wind."],
      ["Raging Companion", "form", 0, "Rage as a bonus action for advantage on Strength and resistance to weapon damage."],
      ["Ravenous Creature", "form", 0, "A bite that can swallow smaller creatures."],
      ["Resilient Companion", "form", 0, "+1 AC and extra hit points equal to your level plus key ability modifier."],
      ["Roguish Creature", "form", 0, "Sneak attack of 1d6, up to 4d6."],
      ["Shadow Creature", "form", 0, "Darkvision and expertise in Stealth in dim light or darkness."],
      ["Skillful Companion", "form", 0, "Two skill, tool or instrument proficiencies."],
      ["Spell-Warded Companion", "form", 0, "Advantage on saves against spells and magical effects."],
      ["Superior Senses", "form", 0, "Darkvision or improved senses."],
      ["Transformative", "form", 0, "Change appearance as an action."],
      ["Vermin Creature", "form", 0, "Climb any surface and poison or web attacks."],
      ["Water Creature", "form", 0, "Swim speed, water breathing and blindsense in water."],
      ["Amorphous Creatures", "other", 0, "Choose a different base companion each time you summon."],
      ["Call the Departed", "other", 0, "Resummon a dismissed companion at a quarter of its hit points.", { cost: 1, applies: ["summon"] }],
      ["Extra Companion", "other", 0, "Gain another companion (only one can be summoned at a time)."],
      ["Link", "other", 0, "A telepathic link to all your companions on the same plane."],
      ["Spell Conduit", "other", 0, "Companions can deliver your touch effects."],
      ["Spell-Linked Companions", "other", 0, "Apply personal sphere effects to a companion within 30 ft."],
      ["Calling", "other", 1, "Call an extraplanar creature of CR up to half your level (10 minutes).", { cost: 2 }],
      ["Diagram", "other", 1, "Bind a called creature with a diagram."],
      ["Divided Companion", "other", 1, "The companion becomes a troop filling a 20 ft square with doubled damage dice."],
      ["Ghostly Creature", "form", 1, "The companion can move through creatures and objects."],
      ["Group Summon", "other", 1, "Summon an additional companion at once.", { cost: 1, applies: ["summon"] }],
      ["Independent Companion", "other", 1, "Allies can direct your companion, and it can act on its own."],
      ["Vanishing Companion", "form", 1, "The companion can hide while observed (11th level)."]
    ]
  },
  {
    key: "creation", name: "Creation",
    summary: "Create and reshape nonmagical objects. Size grows from Tiny to Large as you level.",
    abilities: [
      { key: "alter", name: "Alter", type: "utility", activation: "action", range: "touch", duration: [1, "minute", true],
        summary: "Reshape, repair (1d4 + key ability) or damage a nonmagical unattended object.",
        groups: { alter: "Alter talent" },
        augments: [{ key: "size", label: "Two sizes larger", cost: 1 }, NO_CONC] },
      { key: "create", name: "Create", type: "utility", activation: "action", range: "touch", duration: [1, "minute", true],
        summary: "Create a nonmagical object of vegetable matter in an empty space you can see.",
        augments: [{ key: "size", label: "Two sizes larger", cost: 1 }, NO_CONC] }
    ],
    talents: [
      ["Change Material", "alter", 0, "Turn an object into another material you can create."],
      ["Forge", "alter", 0, "Shape materials into crude items; moving parts have a 30% failure chance."],
      ["Transparency", "alter", 0, "Make a material transparent or one-way."],
      ["Alchemical Creation", "other", 0, "Create acid, alchemist's fire, antitoxin or basic poison."],
      ["Altering Burst", "other", 0, "Alter every unattended object in a 10 ft radius (20 ft with an augment).", { cost: 1, applies: ["alter"] }],
      ["Catapult", "other", 0, "Launch a created object up to 60 ft at a target (Dexterity save)."],
      ["Complex Creation", "other", 0, "Create multi-part themed creations or several objects over time."],
      ["Expanded Materials", "other", 0, "Create stone, then metals, precious metals and gems at higher levels."],
      ["Exquisite Detail", "other", 0, "Create finely detailed objects and convincing forgeries."],
      ["Greater Alter", "other", 0, "Repair and destroy use d8s instead of d4s."],
      ["Magical Creations", "other", 0, "Created objects count as magical."],
      ["Magnify/Minimize", "other", 0, "Grow or shrink an object by one size category."],
      ["Object of Force", "other", 0, "Create weightless objects of solid force."],
      ["Potent Alteration", "other", 0, "Alter magical, worn or held objects and constructs (Constitution save)."],
      ["Precise Destruction", "other", 0, "Disable locks and traps with Alter."],
      ["Restrictive Creation", "other", 0, "Create bindings on a creature to restrain it (Dexterity save)."],
      ["Create Materials", "other", 1, "Instantly create raw material walls, domes and ramps."],
      ["Dissolution", "alter", 1, "Disintegrate nonmagical objects in a 10 ft cube."],
      ["Fabricate", "other", 1, "Craft detailed items at 1 round per 10 cubic feet (11th level)."],
      ["Fleshcraft", "other", 1, "Create or reshape flesh, even of living creatures.", { cost: 1 }],
      ["Permanent Change", "other", 1, "Make Change Material permanent."],
      ["State Shift", "alter", 1, "Turn liquids to solids and back."],
      ["Sustenance", "other", 1, "Create food for creatures equal to your key ability modifier.", { cost: 1 }]
    ]
  },
  {
    key: "dark", name: "Dark",
    summary: "Create magical darkness and grant shadowy powers.",
    grants: ["Darkvision"],
    abilities: [
      { key: "darkness", name: "Darkness", type: "utility", activation: "action", range: 120, template: ["sphere", 15],
        duration: [1, "minute", true],
        summary: "Fill a 15 ft radius with magical darkness that blocks nonmagical light. Darkvision can see through it.",
        groups: { darkness: "Darkness talent" },
        augments: [{ key: "greater", label: "Greater Darkness: 30 ft radius", cost: 1, talent: "Greater Darkness" }, NO_CONC] },
      { key: "meld", name: "Meld", type: "utility", activation: "minute", activationValue: 10, range: "touch", save: "wis",
        duration: [1, "hour", true],
        summary: "Grant a creature a shadow ability, such as darkvision 60 ft (120 ft for 2 spell points).",
        groups: { meld: "Meld talent" },
        augments: [{ key: "action", label: "Meld as an action", cost: 1 }, { key: "darkvision", label: "Darkvision 120 ft", cost: 2 }] }
    ],
    talents: [
      ["Black Lung", "darkness", 0, "Creatures entering must save or be poisoned; poisoned creatures cannot use verbal components."],
      ["Creeping Lethargy", "darkness", 0, "Failed saves limit targets to an action or bonus action; a second failure puts them to sleep."],
      ["Disorienting Darkness", "darkness", 0, "Creatures inside must pass an Intelligence save or move in a random direction."],
      ["Fearful Darkness", "darkness", 0, "Creatures entering must save or be frightened while inside."],
      ["Hungry Darkness", "darkness", 0, "Creatures entering must save or take necrotic damage equal to their Hit Dice."],
      ["Looming Darkness", "darkness", 0, "Creatures inside have disadvantage on Intelligence, Wisdom and Charisma checks and saves."],
      ["Numbing Darkness", "darkness", 0, "Creatures inside have disadvantage on Strength, Dexterity and Constitution checks and saves."],
      ["Pure Darkness", "darkness", 0, "Darkvision works only to 5 ft and other senses are dulled."],
      ["Shadow Slick", "darkness", 0, "Moving faster than half speed requires an Acrobatics check or you fall prone."],
      ["Shadow Tag", "darkness", 0, "Track a number of creatures equal to your proficiency bonus for 8 hours."],
      ["Snagging Darkness", "darkness", 0, "Entering requires a Dexterity save or become restrained."],
      ["Tenebrous Legerdemain", "darkness", 0, "Steal objects from creatures inside with a bonus action."],
      ["Thick Darkness", "darkness", 0, "The darkness is difficult terrain and creatures cannot Dash or Disengage in it."],
      ["Darkvision", "meld", 0, "The target gains darkvision 60 ft (or +30 ft to existing darkvision); 120 ft for 2 spell points.", { builtIn: true }],
      ["Blindfold", "meld", 0, "A shadow band blinds the target (Wisdom save each round ends it)."],
      ["Clearsight", "meld", 0, "Immunity to the penalties of darkness talents."],
      ["Dark Slaughter", "meld", 0, "+1d6 damage (up to 1d12) against foes the target has advantage on or cannot be seen by in darkness."],
      ["Feed on Darkness", "meld", 0, "Gain temporary hit points each round in darkness."],
      ["Hide In Darkness", "meld", 0, "Hide while visible in dim light or darkness."],
      ["Shadow Lurk", "meld", 0, "Create a weightless shadow copy of the target."],
      ["Shadowed Mien", "meld", 0, "Hide the target's appearance and grant advantage on Deception and Intimidation."],
      ["Step Through Darkness", "meld", 0, "Teleport between patches of dim light as a bonus action."],
      ["Clinging Darkness", "other", 0, "Center darkness on a creature or object."],
      ["Directional Darkness", "other", 0, "Darkness blocks light from only one direction.", { cost: 1, applies: ["darkness"] }],
      ["Extinguish", "other", 0, "Put out nonmagical light and contest magical flames."],
      ["Greater Darkness", "other", 0, "Allows a 30 ft radius for 1 spell point."],
      ["Obfuscation", "other", 0, "Things inside your darkness resist scrying."],
      ["Obscure Passage", "other", 0, "Open a temporary hole through a surface.", { cost: 1 }],
      ["Rolling Blackout", "other", 0, "Move your darkness 30 ft with an action or bonus action."],
      ["Shadow Stash", "other", 0, "Store small items in your shadow."],
      ["Wall of Darkness", "other", 0, "Shape darkness as connected 10 ft cubes."],
      ["Animated Shadow", "meld", 1, "Your shadow copy acts as extra limbs (5th level)."],
      ["Eternal Darkness", "other", 1, "Permanent darkness until dispelled (11th level).", { cost: 2, applies: ["darkness"] }],
      ["Lightless Penumbra", "meld", 1, "Shadowed Mien becomes opaque and protects from daylight.", { cost: 1 }],
      ["Midnight", "other", 1, "Darkness spreads over a 2-mile radius (11th level).", { cost: 2, applies: ["darkness"] }],
      ["One With The Void", "other", 1, "Become an incorporeal sphere of darkness that can fly (11th level).", { cost: 2 }],
      ["Pitch Black", "other", 1, "Add Pure Darkness to another darkness talent (5th level).", { cost: 1, applies: ["darkness"] }],
      ["Shadow Walker", "other", 1, "Travel through the plane of shadow at 50 mph (11th level).", { cost: 1 }]
    ]
  },
  {
    key: "death", name: "Death",
    summary: "Strike with negative energy and raise the dead.",
    grants: ["Exhausting Strike"],
    abilities: [
      { key: "ghostStrike", name: "Ghost Strike", type: "save", activation: "action", range: 30, save: "con",
        duration: [0, "inst", false],
        summary: "Strike a creature with negative energy (no effect on undead or constructs). Without another ghost strike talent this is Exhausting Strike: on a failed Constitution save the target gains 1 exhaustion for 10 minutes.",
        groups: { ghostStrike: "Ghost strike" },
        augments: [{ key: "permanent", label: "Exhausting Strike lasts until removed", cost: 1 },
          { key: "cone", label: "Greater Ghost Strike: 30 ft cone", cost: 1, talent: "Greater Ghost Strike" }] },
      { key: "reanimate", name: "Reanimate", type: "utility", activation: "action", range: 30, duration: [10, "minute", true],
        summary: "Raise a corpse as an undead you command with bonus actions. You control up to your proficiency bonus of undead with a CR up to one quarter of your level.",
        groups: { undead: "Undead type", reanimate: "Reanimate talents" }, multi: ["reanimate"],
        augments: [NO_CONC] }
    ],
    talents: [
      ["Exhausting Strike", "ghostStrike", 0, "Constitution save or gain 1 level of exhaustion for 10 minutes (stacking up to your proficiency bonus); 1 spell point makes it last until removed.", { builtIn: true }],
      ["Command Undead", "ghostStrike", 0, "Charm an undead while you concentrate (up to 10 minutes)."],
      ["Curse", "ghostStrike", 0, "A lasting curse (Wisdom save), such as blindness or vulnerability to a damage type.", { cost: 1 }],
      ["Inflict Disease", "ghostStrike", 0, "The target must save or contract a disease.", { cost: 2 }],
      ["Lich Strike", "ghostStrike", 0, "Constitution save or paralyzed for 1 round (longer at higher levels).", { cost: 2 }],
      ["Manipulate Undeath", "ghostStrike", 0, "Deal 1d12 necrotic damage to undead, ignoring immunity, or heal them."],
      ["Necrotic Feeding", "ghostStrike", 0, "Kill a creature at 0 hit points and heal twice its Hit Dice.", { cost: 1 }],
      ["Sickening", "ghostStrike", 0, "Constitution save or poisoned for rounds equal to your proficiency bonus."],
      ["Vampiric Strike", "ghostStrike", 0, "Deal 1d6 necrotic damage and gain that many temporary hit points.", { cost: 1 }],
      ["Vulnerability", "ghostStrike", 0, "Give the target vulnerability to physical damage for up to 1 minute."],
      ["Greater Ghost Strike", "other", 0, "Allows ghost strikes in a 30 ft cone for 1 spell point."],
      ["Killing Curse", "ghostStrike", 1, "Constitution save or die if the target's hit points are below a threshold set by spell points spent.", { cost: 2 }],
      ["Additional Attacks", "reanimate", 0, "Undead gain a bite, claws or slam (1d6).", { cost: 0 }],
      ["Frightful", "reanimate", 0, "Undead gain a frightening glare, wail or visage."],
      ["Grotesque", "reanimate", 0, "Undead gain a bile attack (1d6 poison, 30 ft) or a stench aura."],
      ["Horde of the Dead", "reanimate", 0, "Raise a swarm or troop instead of a single undead."],
      ["Incorporeal", "reanimate", 0, "Undead gain ethereal sight, incorporeal movement or possession."],
      ["Monstrous", "reanimate", 0, "Undead gain Alteration traits."],
      ["Physique", "reanimate", 0, "Undead gain reach, strength, reflexes, toughness or undead fortitude."],
      ["Resistant", "reanimate", 0, "Undead lose vulnerabilities or gain resistances.", { cost: 1 }],
      ["Skilled", "reanimate", 0, "Undead gain proficiencies.", { cost: 1 }],
      ["Trained", "reanimate", 0, "Undead keep the nonmagical class features they had in life."],
      ["Deadly Attacks", "reanimate", 1, "Undead attacks can paralyze, drain or sicken."],
      ["Immunity", "reanimate", 1, "Undead gain condition or damage immunities.", { cost: 1 }],
      ["Immortal", "reanimate", 1, "Destroyed undead collapse and rise again with full hit points.", { cost: 1 }],
      ["Plague of the Dead", "reanimate", 1, "Swarms and troops count as a single undead."],
      ["Prolific", "reanimate", 1, "Undead can create spawn and drain life or strength."],
      ["Vigor", "reanimate", 1, "Undead consume life or regenerate."],
      ["Crawling Claw", "undead", 0, "Animate a severed limb with a 1d4 + 2 claw."],
      ["Ghoul", "undead", 0, "A fresh corpse rises as a ghoul with 1d6 + 3 claws and darkvision."],
      ["Poltergeist", "undead", 0, "An object of the dead becomes a telekinetic poltergeist."],
      ["Shadow", "undead", 0, "A prized object becomes an amorphous shadow."],
      ["Skeleton", "undead", 0, "Bones rise as a skeleton with a 1d6 + 3 slam."],
      ["Specter", "undead", 0, "A flying, incorporeal specter with 1d6 + 3 claws."],
      ["Will-O'-Wisp", "undead", 0, "A dying creature becomes a wisp with a lightning shock."],
      ["Zombie", "undead", 0, "A corpse rises as a slow zombie with a 1d6 + 2 bite."],
      ["Flameskull", "undead", 1, "A spellcaster's skull that shoots fire rays."],
      ["Ghast", "undead", 1, "A speaking ghoul that resists turning."],
      ["Ghost", "undead", 1, "An incorporeal ghost with a withering necrotic touch."],
      ["Mummy", "undead", 1, "A preserved corpse that speaks and slams."],
      ["Vampire Spawn", "undead", 1, "A spider-climbing spawn with a draining bite."],
      ["Wight", "undead", 1, "A wight that resists nonsilvered weapons."],
      ["Wraith", "undead", 1, "A flying, incorporeal wraith."],
      ["Corpse Bomb", "other", 0, "Detonate a corpse or controlled undead as a ghost strike in a 20 ft radius."],
      ["Corpse Manipulation", "other", 0, "Reshape, preserve or decompose corpses."],
      ["Dark Sacrifice", "other", 0, "As a reaction, sacrifice a nearby undead to absorb damage.", { cost: 1 }],
      ["Gravetongue", "other", 0, "Speak with a corpse or undead for 10 minutes.", { cost: 1 }],
      ["Icy Grip", "other", 0, "Your undead can deliver your ghost strikes."],
      ["Master's Presence", "other", 0, "Command your undead telepathically within 300 ft."],
      ["Necrotic Senses", "other", 0, "See and hear through your undead within 120 ft."],
      ["Astral Projection", "other", 1, "Project yourself and others to the Astral Plane (11th level).", { cost: 1 }],
      ["Astral Travel", "other", 1, "Travel astrally to other planes (15th level).", { cost: 1 }],
      ["Permanent Undead", "other", 1, "Reanimated undead become permanent (5th level).", { cost: 3, applies: ["reanimate"] }],
      ["Possession", "other", 1, "Project your spirit into a creature to control it (11th level).", { cost: 2 }],
      ["Practitioner Training", "reanimate", 1, "Reanimated warriors keep martial talents."],
      ["Project Spirit", "other", 1, "Project your spirit on the Ethereal Plane for 1 minute (11th level).", { cost: 2 }],
      ["Spellcaster Training", "reanimate", 1, "Reanimated casters keep some magic."],
      ["Soul Trap", "other", 1, "Trap the soul of a recently dead creature (15th level).", { cost: 3 }],
      ["Summon Spirit", "other", 1, "Call the soul of a dead creature to speak with it.", { cost: 2 }]
    ]
  },
  {
    key: "destruction", name: "Destruction",
    summary: "Blast enemies with raw magical energy shaped by blast type and blast shape talents.",
    abilities: [
      { key: "blast", name: "Destructive Blast", type: "save", activation: "action", range: 30, save: "dex",
        duration: [0, "inst", false], damage: { key: "blast", types: BLAST_TYPES },
        summary: "Deal 1d8 damage (2d8 at 5th, 3d8 at 11th, 4d8 at 17th level) to one creature or object within 30 ft. Apply one blast type and one blast shape. Augment with 1 spell point to deal 1d8 + 1d8 per 2 character levels instead.",
        groups: { blastType: "Blast type", blastShape: "Blast shape" },
        augments: [{ key: "empower", label: "Empowered: 1d8 + 1d8 per 2 levels", cost: 1 }] },
      { key: "blastAttack", name: "Destructive Blast (Attack)", type: "attack", activation: "action", range: 30,
        duration: [0, "inst", false], damage: { key: "blast", types: BLAST_TYPES }, hidden: true,
        summary: "Destructive blast delivered with a spell attack (Ray or Tether blast shape)." }
    ],
    talents: [
      ["Form-Breaking", "blastType", 0, "Bludgeoning; targets have disadvantage on Athletics and Acrobatics until your next turn.", { dt: "bludgeoning", free: "Alteration" }],
      ["Poison", "blastType", 0, "Poison; targets are poisoned until your next turn.", { dt: "poison", free: "Alteration" }],
      ["Restraining", "blastType", 0, "Bludgeoning; targets are grappled until the end of your next turn.", { dt: "bludgeoning", free: "Conjuration" }],
      ["Spectral", "blastType", 0, "Slashing; targets count as flanked until your next turn.", { dt: "slashing", free: "Conjuration" }],
      ["Corrosive", "blastType", 0, "Acid; targets take more acid damage equal to the dice rolled at the start of your next turn.", { dt: "acid", free: "Creation" }],
      ["Physical", "blastType", 0, "Bludgeoning, piercing or slashing damage of your choice.", { dt: "bludgeoning", free: "Creation" }],
      ["Beshadowed", "blastType", 0, "Cold; targets struggle to see and treat creatures as having half cover.", { dt: "cold", free: "Dark" }],
      ["Ink", "blastType", 0, "Necrotic; disadvantage on saves against your Dark sphere until your next turn.", { dt: "necrotic", free: "Dark" }],
      ["Draining", "blastType", 0, "Necrotic; Constitution save or gain exhaustion for a few rounds.", { dt: "necrotic", free: "Death" }],
      ["Necrotic", "blastType", 0, "Necrotic; disadvantage on saves against your Death sphere until your next turn.", { dt: "necrotic", free: "Death" }],
      ["Psionic", "blastType", 0, "Psychic; targets have disadvantage on attacks against you until your next turn.", { dt: "psychic", free: "Divination" }],
      ["Psychic Deluge", "blastType", 0, "Psychic; Intelligence save or only an action or bonus action next turn.", { dt: "psychic", free: "Divination" }],
      ["Degrading", "blastType", 0, "Force; targets' attacks count as magical until your next turn.", { dt: "force", free: "Enhancement" }],
      ["Hindering", "blastType", 0, "Necrotic; speed reduced by 10 ft for 1 minute (stacks).", { dt: "necrotic", free: "Enhancement" }],
      ["Cursed", "blastType", 0, "Necrotic; disadvantage on the next check or save before your next turn ends.", { dt: "necrotic", free: "Fate" }],
      ["Tribunal", "blastType", 0, "Radiant; disadvantage on saves against your Fate sphere until your next turn.", { dt: "radiant", free: "Fate" }],
      ["Bewildering", "blastType", 0, "Psychic; disadvantage on saves against your Illusion sphere until your next turn.", { dt: "psychic", free: "Illusion" }],
      ["Shadow", "blastType", 0, "Any damage type, but only half damage.", { dt: "force", free: "Illusion" }],
      ["Invigorating", "blastType", 0, "Radiant; you gain temporary hit points equal to the dice rolled.", { dt: "radiant", free: "Life" }],
      ["Vivacity", "blastType", 0, "Radiant; advantage against undead, which have disadvantage on the save.", { dt: "radiant", free: "Life" }],
      ["Illuminating", "blastType", 0, "Radiant; targets glow and have disadvantage on Stealth until your next turn.", { dt: "radiant", free: "Light" }],
      ["Radiant", "blastType", 0, "Radiant; one target has disadvantage on attacks until your next turn.", { dt: "radiant", free: "Light" }],
      ["Charming", "blastType", 0, "Psychic; Charisma save or charmed until your next turn.", { dt: "psychic", free: "Mind" }],
      ["Frightful", "blastType", 0, "Psychic; Wisdom save or frightened until your next turn.", { dt: "psychic", free: "Mind" }],
      ["Bludgeoning", "blastType", 0, "Bludgeoning; targets are pushed 5 ft away.", { dt: "bludgeoning", free: "Nature" }],
      ["Bramble", "blastType", 0, "Piercing; Dexterity save or grappled by thorny vines.", { dt: "piercing", free: "Nature" }],
      ["Drowning", "blastType", 0, "Cold; targets are soaked and weaker against water effects.", { dt: "cold", free: "Nature" }],
      ["Fire", "blastType", 0, "Fire; Dexterity save or catch fire, taking 1d8 each round.", { dt: "fire", free: "Nature" }],
      ["Razor Wind", "blastType", 0, "Slashing; -1 AC until the end of your next turn.", { dt: "slashing", free: "Nature" }],
      ["Shrapnel", "blastType", 0, "Piercing; the area becomes caltrops until your next turn.", { dt: "piercing", free: "Nature" }],
      ["Confining", "blastType", 0, "Force; Strength save or cannot move closer until your next turn.", { dt: "force", free: "Protection" }],
      ["Warding", "blastType", 0, "Bludgeoning; you resist the next attack from the target before your next turn.", { dt: "bludgeoning", free: "Protection" }],
      ["Gravity", "blastType", 0, "Force; others have advantage on attacks against the target until your next turn.", { dt: "force", free: "Telekinesis" }],
      ["Kinetic", "blastType", 0, "Force; Strength save or fall prone.", { dt: "force", free: "Telekinesis" }],
      ["Entropic", "blastType", 0, "Necrotic; Constitution save or disadvantage on physical saves for 1 round.", { dt: "necrotic", free: "Time" }],
      ["Slowing", "blastType", 0, "Force; Wisdom save or only an action or bonus action for 1 round.", { dt: "force", free: "Time" }],
      ["Chromatic", "blastType", 0, "Roll a d6 for acid, cold, fire, lightning, poison or thunder; may trigger wild magic.", { dt: "fire", free: "Universal" }],
      ["Disrupting", "blastType", 0, "Force; disadvantage on concentration saves until your next turn.", { dt: "force", free: "Universal" }],
      ["Siphoning", "blastType", 0, "Psychic; gain a temporary spell point when you damage a spellcaster.", { dt: "psychic", free: "Universal" }],
      ["Dismissing", "blastType", 0, "Force; advantage against summoned creatures, which have disadvantage on the save.", { dt: "force", free: "Warp" }],
      ["Teleporting", "blastType", 0, "Force; Wisdom save or teleported 5 ft in a direction you choose.", { dt: "force", free: "Warp" }],
      ["Gale", "blastType", 0, "Thunder; disadvantage on saves against your wind effects until your next turn.", { dt: "thunder", free: "Weather" }],
      ["Ice", "blastType", 0, "Cold; speed reduced by 10 ft for 1 minute.", { dt: "cold", free: "Weather" }],
      ["Lightning", "blastType", 0, "Lightning; no reactions until your next turn; better against metal armor.", { dt: "lightning", free: "Weather" }],
      ["Scorching", "blastType", 0, "Fire; extra damage equal to your proficiency bonus that ignores resistance.", { dt: "fire", free: "Weather", bonus: "@prof" }],
      ["Thunder", "blastType", 0, "Thunder; Constitution save or deafened for 1 minute.", { dt: "thunder", free: "Weather" }],
      ["Aura", "blastShape", 0, "A 10 ft aura around you; each creature inside makes a Dexterity save for half.", { template: ["radius", 10] }],
      ["Blade", "blastShape", 0, "Imbue a weapon or 20 pieces of ammunition to apply the blast type on hits."],
      ["Chain Blast", "blastShape", 0, "The blast arcs to further targets (up to your proficiency bonus) within 30 ft of each other."],
      ["Explosive Orb", "blastShape", 0, "Affect a 5 ft cube; can create a globe that explodes later.", { template: ["cube", 5],
        shapeOptions: [{ key: "orbSphere", label: "20 ft radius sphere instead", cost: 1, template: ["sphere", 20] }] }],
      ["Leap", "blastShape", 0, "A 5 ft by 10 ft line after which you teleport to its end.", { template: ["line", 10, 5],
        shapeOptions: [{ key: "leapLong", label: "Line up to your blast range (30 ft)", cost: 1, template: ["line", 30, 5] }] }],
      ["Ray", "blastShape", 0, "Make a ranged spell attack instead of a save; augment for more rays.", { attack: true }],
      ["Retribution", "blastShape", 0, "As a reaction when damaged, blast the attacker."],
      ["Sculpt", "blastShape", 0, "A 5 ft radius; augment for a 30 ft cone or 120 ft line.", { template: ["sphere", 5],
        shapeOptions: [{ key: "sculptCone", label: "30 ft cone", cost: 1, template: ["cone", 30] },
          { key: "sculptLine", label: "120 ft by 5 ft line", cost: 1, template: ["line", 120, 5] }] }],
      ["Sphere", "blastShape", 0, "A 5 ft sphere that lasts 1 round and moves 30 ft as a bonus action.", { template: ["sphere", 2.5] }],
      ["Tether", "blastShape", 0, "Spell attack that tethers the target within 30 ft; deal damage again as a bonus action.", { attack: true }],
      ["Wall", "blastShape", 0, "5 ft by 5 ft wall panels (2 at 5th, 4 at 11th, 8 at 17th level) that blast creatures passing through (concentration, 1 minute).",
        { template: ["wall", 5, 1, 5], shapeOptions: [{ key: "wallLarge", label: "Larger panels (10 ft by 10 ft)", cost: 1, template: ["wall", 10, 1, 10] }] }],
      ["Blaster Adept", "other", 0, "Add your key ability modifier to damage of one chosen damage type."],
      ["Energy Weapon", "other", 0, "Conjure a magical weapon that deals your blast type damage (concentration, 1 minute)."],
      ["Epicenter", "other", 0, "You are immune to your own destructive blasts."],
      ["Extra Blast Type", "other", 0, "Gain three blast types you do not have. Can be taken more than once."],
      ["Guided Strike", "other", 0, "Advantage on destructive blast spell attacks."],
      ["Selective Blast", "other", 0, "Exclude one creature from an instantaneous blast (more with an augment).", { cost: 1, applies: ["blast", "blastAttack"] }],
      ["Calamity", "blastShape", 1, "Sculpt becomes a 500 ft line, a 90 ft cone or everything within 30 ft (11th level).", { cost: 1, template: ["radius", 30],
        shapeOptions: [{ key: "calamityCone", label: "90 ft cone", cost: 1, template: ["cone", 90] },
          { key: "calamityLine", label: "500 ft by 5 ft line", cost: 1, template: ["line", 500, 5] }] }],
      ["Cloud", "blastShape", 1, "A lingering 15 ft cloud of blast damage for up to 10 minutes (5th level).", { cost: 3, template: ["cylinder", 15, null, 15] }],
      ["Disintegrate", "blastType", 1, "Force damage + your level; creatures reduced to 0 hit points turn to dust (5th level).", { dt: "force", cost: 1, bonus: "@details.level" }],
      ["Penetrating Blast", "other", 1, "Ignore resistance to the blast's damage type (5th level).", { cost: 1, applies: ["blast", "blastAttack"] }]
    ]
  },
  {
    key: "divination", name: "Divination",
    summary: "Learn hidden things and gain supernatural senses.",
    abilities: [
      { key: "divine", name: "Divine", type: "utility", activation: "minute", activationValue: 10, range: 120,
        duration: [10, "minute", true],
        summary: "Divine information within 120 ft using one divine talent. Most barriers do not stop it.",
        groups: { divine: "Divination" },
        augments: [{ key: "action", label: "Divine as an action", cost: 1 }] },
      { key: "sense", name: "Sense", type: "utility", activation: "action", range: "self", duration: [1, "hour", true],
        summary: "Gain a supernatural sense out to 30 ft.",
        groups: { sense: "Sense" },
        augments: [{ key: "range", label: "Sense range 120 ft", cost: 1 }] }
    ],
    talents: [
      ["Detect Monstrosity", "divine", 0, "Sense monstrosities and identify them with Nature."],
      ["Detect Shapechanger", "divine", 0, "See shapechanger auras and learn their true form."],
      ["Detect Aberrations", "divine", 0, "Sense aberrations and identify them."],
      ["Detect Summons", "divine", 0, "Sense extraplanar creatures and their home plane."],
      ["Detect Constructs", "divine", 0, "Sense constructs and identify their kind."],
      ["Detect Oozes", "divine", 0, "Sense oozes within range."],
      ["Object Reading", "divine", 0, "Learn about an object's last owner."],
      ["Detect Fiends", "divine", 0, "Sense fiends and fiendish heritage."],
      ["Detect Shadows", "divine", 0, "Sense creatures and magic of the plane of shadow."],
      ["Detect Curse", "divine", 0, "See curses and learn their properties."],
      ["Detect Undead", "divine", 0, "Sense undead and identify their type."],
      ["Detect Dragons", "divine", 0, "Sense dragons and draconic heritage."],
      ["Detect Hostility", "divine", 0, "Know where damage is dealt and track its source."],
      ["Detect Enhancement", "divine", 0, "See temporary bonuses and penalties."],
      ["Detect Information", "divine", 0, "Reroll a failed Intelligence check as a reaction.", { cost: 1 }],
      ["Detect Alignment", "divine", 0, "Learn a creature's alignment (Charisma save)."],
      ["Detect Background", "divine", 0, "Learn a creature's trait, ideal, bond or flaw (Charisma save)."],
      ["Detect Illusions", "divine", 0, "Make a free check to see through illusions."],
      ["Detect Secrets", "divine", 0, "Find hidden doors and caches.", { cost: 1 }],
      ["Detect Affliction", "divine", 0, "See diseases and poisons."],
      ["Detect Life", "divine", 0, "Sense living creatures and their condition."],
      ["Detect Celestials", "divine", 0, "Sense celestials and celestial heritage."],
      ["Ultravision", "divine", 0, "Advantage on Perception and a free check each turn."],
      ["Detect Charm", "divine", 0, "See charms and compulsions."],
      ["Detect Psionic Potential", "divine", 0, "Sense psionic ability."],
      ["Detect Thoughts", "divine", 0, "Advantage on Insight; read surface thoughts with an augment."],
      ["Detect Elementals", "divine", 0, "Sense elementals."],
      ["Detect Nature", "divine", 0, "Sense aspects of nature matching your Nature packages."],
      ["Augury", "divine", 0, "Learn if an action is likely good, bad or mixed.", { cost: 1 }],
      ["Detect Protection", "divine", 0, "Learn the lowest and highest AC or saves among creatures."],
      ["Detect Density", "divine", 0, "See the density and weight of things."],
      ["Viewing", "divine", 0, "See and hear from another point in range.", { cost: 1 }],
      ["Foresight", "divine", 0, "Gain a d4 to add to rolls over 24 hours."],
      ["Hindsight", "divine", 0, "See what happened in the area in the last hour."],
      ["Detect Magic", "divine", 0, "See magic auras and identify them with Arcana."],
      ["Detect Spellcaster", "divine", 0, "Learn how strong a spellcaster is."],
      ["Dowsing", "divine", 0, "Locate a specific creature or object in range.", { cost: 1 }],
      ["Detect Portal", "divine", 0, "Sense portals and extradimensional spaces."],
      ["Detect Teleportation", "divine", 0, "Sense recent teleportation."],
      ["Aeriology", "divine", 0, "Gather local rumors as if spending hours talking.", { cost: 1 }],
      ["Detect Weather", "divine", 0, "Predict the natural weather for 48 hours."],
      ["Blindfolded Oracle", "sense", 0, "Blindsight within your sense range while your eyes are closed.", { cost: 1 }],
      ["Comprehend Languages", "sense", 0, "Understand languages within range."],
      ["Discern Individual", "sense", 0, "Advantage on checks to recall a creature's abilities."],
      ["Discern Scrying", "sense", 0, "Notice scrying attempts."],
      ["Foreshadow", "sense", 0, "Advantage on initiative and immunity to surprise advantage."],
      ["Ghost Sight", "sense", 0, "Advantage on noticing invisible and ethereal creatures."],
      ["Nature Sense", "sense", 0, "Proficiency or expertise in Nature and Survival."],
      ["Scent", "sense", 0, "Pinpoint creatures by scent."],
      ["See Hazard", "sense", 0, "+5 to passive Perception against traps.", { cost: 1 }],
      ["Sense Magic", "sense", 0, "Constant magic detection without concentration.", { cost: 1 }],
      ["Shared Perception", "sense", 0, "Share your senses with allies.", { cost: 1 }],
      ["Sniper's Eye", "sense", 0, "Ignore a source of disadvantage on ranged attacks."],
      ["Tremorsense", "sense", 0, "Tremorsense within your sense range."],
      ["Expanded Divinations", "other", 0, "Gain three more divinations. Can be taken more than once."],
      ["Fast Divinations", "other", 0, "Divine in 1 minute."],
      ["Invasive Divinations", "other", 0, "Disadvantage on saves against your divinations."],
      ["Sensory Overload", "other", 0, "Blind yourself and a target, dealing psychic damage equal to your level.", { cost: 1 }],
      ["Advanced Senses", "sense", 1, "Gain lifesense, thoughtsense and similar senses (11th level)."],
      ["Delve For Knowledge", "divine", 1, "Ask a question with a good chance of a true answer.", { cost: 2 }],
      ["Detect Planeshift", "divine", 1, "Learn the destination of planar travel."],
      ["Find Location", "divine", 1, "Locate any creature or object across planes.", { cost: 3 }],
      ["Penetrating Divination", "other", 1, "Divination passes through thicker barriers."],
      ["Read Omens", "divine", 1, "Receive cryptic advice about a goal.", { cost: 1 }],
      ["Scrying", "divine", 1, "Observe a creature at any distance.", { cost: 2 }],
      ["Scrying, Greater", "divine", 1, "Move your scrying sensor freely.", { cost: 1 }],
      ["Track Aura", "divine", 1, "Follow lingering auras like tracks."],
      ["True Seeing", "sense", 1, "See through darkness, illusions and invisibility.", { cost: 2 }],
      ["Unobscured Vision", "sense", 1, "See through 30 ft of solid matter.", { cost: 3 }]
    ]
  },
  {
    key: "enhancement", name: "Enhancement",
    summary: "Improve or weaken creatures and objects.",
    abilities: [
      { key: "enhance", name: "Enhance", type: "utility", activation: "action", range: 30, duration: [10, "minute", true],
        summary: "Improve a creature or object using an enhancement talent. Unwilling creatures make a Wisdom save.",
        groups: { enhancement: "Enhancement" },
        augments: [NO_CONC] },
      { key: "degrade", name: "Degrade", type: "save", activation: "action", range: 30, save: "wis", duration: [10, "minute", true],
        summary: "Weaken a creature or object using an enhancement talent. The target repeats the save at the end of each turn.",
        groups: { enhancement: "Enhancement" },
        augments: [NO_CONC] }
    ],
    talents: [
      ["Animate Object", "enhancement", 0, "Enhance: animate a Tiny object (AC 18, 20 hp). Degrade: restrain a construct."],
      ["Bestow Intelligence", "enhancement", 0, "Enhance: give a mindless creature Intelligence 10 and a language. Degrade: reduce a construct's Intelligence to 2."],
      ["Keen Weapon", "enhancement", 0, "Enhance: a weapon scores critical hits on 19-20. Degrade: its damage dice count as 1s."],
      ["Pursuant Ammunition", "enhancement", 0, "Enhance: ranged attacks ignore one level of cover. Degrade: ranged attacks have disadvantage."],
      ["Versatile Weapon", "enhancement", 0, "A weapon counts as a chosen material."],
      ["Energy Weapon", "enhancement", 0, "A weapon deals an extra 1d6 of a chosen energy type."],
      ["Enhance Equipment", "enhancement", 0, "Enhance: equipment becomes magical with a bonus of half your proficiency bonus. Degrade: suppress magical bonuses."],
      ["Corrosive Poison", "enhancement", 0, "Poison damage becomes acid damage."],
      ["Enhance Virulence", "enhancement", 0, "Poisons are harder or easier to resist."],
      ["Enhance Capacity", "enhancement", 0, "Double or quarter carrying capacity."],
      ["Improved Flexibility", "enhancement", 0, "Squeeze as one size smaller or larger."],
      ["Ignore Exhaustion", "enhancement", 0, "Ignore exhaustion levels up to your proficiency bonus."],
      ["Resist Debilitation", "enhancement", 0, "Ignore ability score reductions."],
      ["Manipulate Hardness", "enhancement", 0, "Enhance: resistance to physical damage. Degrade: vulnerability."],
      ["Enhance Focus", "enhancement", 0, "Enhance: treat skill checks as 10 or better. Degrade: lose proficiency on checks."],
      ["Enhance Mind", "enhancement", 0, "Advantage or disadvantage on Intelligence, Wisdom and Charisma checks."],
      ["Muffle Sound", "enhancement", 0, "Muffle or amplify the target's sounds."],
      ["Enhance Physique", "enhancement", 0, "Advantage or disadvantage on Strength, Dexterity and Constitution checks."],
      ["Superior Reflexes", "enhancement", 0, "Advantage on initiative and a free opportunity attack, or the reverse."],
      ["Speed Control", "enhancement", 0, "Enhance: +10 ft speed (more at higher levels). Degrade: halve a speed."],
      ["Staunch Resistance", "enhancement", 0, "Enhance: proficiency in a save. Degrade: disadvantage on saves."],
      ["Steal Senses", "enhancement", 0, "Degrade: blind, deafen or remove a special sense.", { cost: 1 }],
      ["Still Tongue", "enhancement", 0, "Degrade: the target cannot speak or use verbal components."],
      ["Weight Control", "enhancement", 0, "Change the weight of a creature or object."],
      ["Dual Enhancement", "other", 0, "Apply two options or two talents with one casting.", { cost: 1, applies: ["enhance", "degrade"] }],
      ["Bestow Sentience", "other", 1, "Grant lasting sentience to beasts, plants or items (11th level).", { cost: 3 }],
      ["Referential Enhancements", "other", 1, "Mass enhancements over a 30 ft sphere for a week (15th level).", { cost: 2 }],
      ["Reverse Gravity", "other", 1, "Reverse gravity in ten 10 ft cubes (15th level).", { cost: 2 }]
    ]
  }
];
